from .base_page import BasePage
from .locators import RegisterPageLocators, PatientCardLocators, WorkJournalLocators
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from time import sleep
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.by import By
from random import randrange
import datetime
from datetime import datetime, timedelta, date
import string
import random


class RegisterPage(BasePage):
    patient_id_child = None
    patient_id_bomj = None
    patient_id_foreigner = None
    patient_id_citizen = None
    gen_choice = random.choice(['female', 'male'])
    gen_choice1 = random.choice(['1', '2'])
    mo_choice = random.choice(['170000000003', '170000000105', '170000000004', '170000000008', '170000000009'])
    mo_choice1 = random.choice(['20000000025', '20000000011', '20000000012', '20000000070', '20000000135'])
    mo_rec_choice = random.choice(['170000000013', '170000000058', '170000000174', '170000000233', '170000000243', '170000000255'])
    locality_choice = random.choice(['170000000020', '170000000008', '170000000032', '170000000085', '170000000242', '170000000253'])
    aidc_center_choice = random.choice(['1', '2', '3', '4', '5', '6', '7', '8', '10', '28', '29'])
    street_choice = random.choice(['Назарбаев', 'Абай', 'Конаев', 'Кабанбай батыр'])
    surname = ''.join(random.choices(string.ascii_uppercase, k=10))
    name = ''.join(random.choices(string.ascii_uppercase, k=5))
    midname = ''.join(random.choices(string.ascii_uppercase, k=10))
    numbers3 = ''.join(random.choices(string.digits, k=5))
    numbers4 = ''.join(random.choices(string.digits, k=5))
    numbers5 = ''.join(random.choices(string.digits, k=5))
    contacting_num = random.randint(1, 4)
    today = datetime.now().strftime('%d.%m.%Y')
    d1 = datetime.strptime('01.01.1990', '%d.%m.%Y')
    d2 = datetime.strptime('01.12.2005', '%d.%m.%Y')
    delta = d2 - d1
    int_delta = delta.days
    birthday = datetime.strftime(d1 + timedelta(randrange(int_delta)), '%d.%m.%Y')
    years_choice = random.choice(['1', '2', '3'])
    month_choice = random.choice(['1', '2', '3', '4', '5', '6', '7', '8', '10', '9', '11'])
    organ_mat_type_choice = random.choice(['1', '2', '3', '4', '5'])
    hiv_status_choice = random.choice(['1', '2', '3'])
    smth_random = ''.join(random.choices(string.ascii_uppercase, k=10))
    country_choice = random.choice(['1', '2', '3', '4', '5', '6', '7', '8', '10', '9', '11'])
    manip_emerg_date = datetime.strftime(datetime.now() - timedelta(days=200), '%d.%m.%Y')
    eighty_days_ago = datetime.strftime(datetime.now() - timedelta(days=80), '%d.%m.%Y')
    sixty_days_ago = datetime.strftime(datetime.now() - timedelta(days=60), '%d.%m.%Y')
    fifty_days_ago = datetime.strftime(datetime.now() - timedelta(days=50), '%d.%m.%Y')
    thirty_days_ago = datetime.strftime(datetime.now() - timedelta(days=30), '%d.%m.%Y')
    twenty_days_ago = datetime.strftime(datetime.now() - timedelta(days=20), '%d.%m.%Y')
    regis_date = datetime.strftime(datetime.now() - timedelta(days=50), '%d.%m.%Y')
    deregis_date = datetime.strftime(datetime.now() - timedelta(days=5), '%d.%m.%Y')
    ib_date = datetime.strftime(datetime.now() - timedelta(days=180), '%d.%m.%Y')
    diagnosis_date = datetime.strftime(datetime.now() - timedelta(days=190), '%d.%m.%Y')
    thirty_days_forward = datetime.strftime(datetime.now() + timedelta(days=30), '%d.%m.%Y')
    fifty_days_forward = datetime.strftime(datetime.now() + timedelta(days=50), '%d.%m.%Y')
    expiration_date = datetime.strftime(datetime.now() + timedelta(days=365), '%d.%m.%Y')


    def register_new_child_and_edit_card(self):
        # автозаполнение формы регистрации для ребенка

        res_code_choice = random.choice(['47', '48', '11', '22'])
        self.browser.execute_script(f"{RegisterPageLocators.RESEARCH_CODE}.dropdown('set selected', '{res_code_choice}');")
        d1 = datetime.strptime('01.01.2005', '%d.%m.%Y')
        d2 = datetime.strptime('01.12.2021', '%d.%m.%Y')
        delta = d2 - d1
        int_delta = delta.days
        random_date = d1 + timedelta(randrange(int_delta))
        first_numbers = random_date.strftime('%y%m%d')
        p_birthday = random_date.strftime('%d.%m.%Y')
        others = random.randrange(100000, 999999)
        iin = f'{first_numbers}{others}'
        self.browser.find_element(*RegisterPageLocators.PATIENT_IIN).send_keys(iin)
        # self.browser.execute_script(f"{RegisterPageLocators.ANONIMOUS}.checkbox('set checked');")
        p_surname = ''.join(random.choices(string.ascii_uppercase, k=9))
        self.browser.find_element(*RegisterPageLocators.PATIENT_SURNAME).send_keys(p_surname)
        p_name = ''.join(random.choices(string.ascii_uppercase, k=6))
        self.browser.find_element(*RegisterPageLocators.PATIENT_NAME).send_keys(p_name)
        p_midname = ''.join(random.choices(string.ascii_uppercase, k=10))
        self.browser.find_element(*RegisterPageLocators.PATIENT_MIDNAME).send_keys(p_midname)
        # self.browser.execute_script(f"$('{RegisterPageLocators.BIRTH_DATE}').val('{birthday}')")
        self.browser.execute_script(f"$('#general_data_birth').val('{p_birthday}')")
        self.browser.execute_script(f"{RegisterPageLocators.PATIENT_GENDER}.dropdown('set selected', '{self.gen_choice}');")
        self.browser.execute_script(f"{RegisterPageLocators.EMERGENCE_AREA}.dropdown('set selected', '3');")
        sleep(1)
        self.browser.execute_script("$('div[data-field=general_data_adm_obl_viyav] input.search').focus();")
        sleep(1)
        self.browser.execute_script("$('div[data-field=general_data_adm_obl_viyav] input.search').click();")
        sleep(1)
        self.browser.execute_script("$('div[data-field=general_data_adm_obl_viyav] .ui.dropdown').dropdown('set selected', '33');")
        sleep(1)
        self.browser.execute_script("$('div[data-field=general_data_adm_obl_viyav] .ui.dropdown').dropdown('hide');")
        self.browser.execute_script(f"{RegisterPageLocators.PATIENT_CITIZENSHIP}.dropdown('set selected', '1');")
        child_status_choice = random.choice(['1', '2', '3', '4', '5'])
        self.browser.execute_script(f"{RegisterPageLocators.CHILD_STATUS}.dropdown('set selected', '{child_status_choice}');")
        soc_status_choice = random.choice(['3', '4'])
        self.browser.execute_script(f"{RegisterPageLocators.SOCIAL_STATUS}.dropdown('set selected', '{soc_status_choice}');")
        self.browser.execute_script(f"{RegisterPageLocators.MED_ORG}.dropdown('set selected', '{self.mo_choice}');")
        self.browser.execute_script(f"{RegisterPageLocators.REGIS_AREA}.dropdown('set selected', '5');")
        self.browser.execute_script(f"{RegisterPageLocators.REGIS_UNIT_AREA}.click();")
        self.browser.execute_script(f"{RegisterPageLocators.REGIS_UNIT_AREA}.dropdown('set selected', '180');")
        self.browser.execute_script(f"{RegisterPageLocators.REGIS_UNIT_AREA}.dropdown('hide');")
        # self.browser.execute_script(f"{RegisterPageLocators.REGIS_UNIT_AREA}.dropdown('set selected', '180');")
        self.browser.execute_script(f"{RegisterPageLocators.REGIS_LOCALITY}.dropdown('set selected', '177');")
        self.browser.execute_script(f"{RegisterPageLocators.REGIS_PLACE}.dropdown('set selected', '2');")
        self.browser.find_element(*RegisterPageLocators.REGIS_STREET).send_keys(self.street_choice)
        self.browser.find_element(*RegisterPageLocators.REGIS_HOUSE).send_keys(55)
        self.browser.find_element(*RegisterPageLocators.REGIS_APT).send_keys(44)
        self.browser.find_element(*RegisterPageLocators.REGIS_PHONE_NO).send_keys(87273456987)
        self.browser.execute_script(f"{RegisterPageLocators.RESID_AREA}.dropdown('set selected', '3');")
        self.browser.execute_script(f"{RegisterPageLocators.RESID_UNIT_AREA}.click();")
        self.browser.execute_script(f"{RegisterPageLocators.RESID_UNIT_AREA}.dropdown('set selected', '33');")
        self.browser.execute_script(f"{RegisterPageLocators.RESID_UNIT_AREA}.dropdown('hide');")
        self.browser.execute_script(f"{RegisterPageLocators.RESID_UNIT_AREA}.dropdown('set selected', '33');")
        self.browser.execute_script(f"{RegisterPageLocators.RESID_LOCALITY}.dropdown('set selected', '170000000008');")
        self.browser.execute_script(f"{RegisterPageLocators.RESID_PLACE}.dropdown('set selected', '2');")
        self.browser.find_element(*RegisterPageLocators.RESID_STREET).send_keys(self.street_choice)
        self.browser.find_element(*RegisterPageLocators.RESID_HOUSE).send_keys(25)
        self.browser.find_element(*RegisterPageLocators.RESID_APT).send_keys(45)
        self.browser.find_element(*RegisterPageLocators.RESID_PHONE_NO).send_keys(87273456789)
        self.browser.execute_script(f"{RegisterPageLocators.RESID_MED_ORG}.dropdown('set selected', '170000000558');")
        self.browser.execute_script(f"{RegisterPageLocators.RETROSPECTIVE_CHILD}.checkbox('set checked');")
        sleep(2)
        self.browser.find_element(*RegisterPageLocators.MOTHERS_SURNAME).send_keys(self.surname)
        self.browser.find_element(*RegisterPageLocators.MOTHERS_NAME).send_keys(self.name)
        self.browser.find_element(*RegisterPageLocators.MOTHERS_MIDNAME).send_keys(self.midname)
        self.browser.find_element(*RegisterPageLocators.MOTHERS_IB_NO).send_keys(self.numbers5)
        self.browser.find_element(*RegisterPageLocators.IB_NO_DATE).send_keys(self.ib_date)
        # self.browser.take_screenshot()
        self.browser.find_element(*RegisterPageLocators.REGISTER_SAVE_BTN).click()
        sleep(2)
        # self.browser.find_element(*RegisterPageLocators.EDIT_PATIENT_CARD).click()
        # self.browser.find_element(*RegisterPageLocators.REGIS_APT2).send_keys(77)
        # self.browser.find_element(*RegisterPageLocators.ERROR_REGIS_ADDRESS_SAVE).click()
        self.browser.execute_script(f"{RegisterPageLocators.REASON_NOT_EPID}.dropdown('set selected', '3');")
        self.browser.execute_script(f"{RegisterPageLocators.REASON_NOT_DISP_REG}.dropdown('set selected', '6');")
        self.browser.find_element(*RegisterPageLocators.PATIENT_CARD_SAVE).click()
        sleep(2)

        # id_url = self.browser.current_url
        # url_part = id_url.split('/')[5]
        # patient_id_child = url_part[:12]
        #
        # # # WebDriverWait(browser, 5).until(EC.element_to_be_clickable(*PatientCardLocators.OPEN_PATIENT_MENU)).click()
        # self.browser.execute_script(f"{PatientCardLocators.OPEN_PATIENT_MENU}.sidebar('show')")  # Развернули карту пациента
        # sleep(1)
        # self.browser.execute_script(f"{PatientCardLocators.LAB_RESEARCH}.click()")  # Открываем Эпидемиологический анамнез
        # sleep(2)
        # self.browser.find_element(*PatientCardLocators.IFA_OGC_ADD).click()
        # sleep(2)
        # self.browser.execute_script(f"{PatientCardLocators.IFA_MED_ORG}.dropdown('set selected', '{self.mo_choice}');")
        # self.browser.find_element(*PatientCardLocators.SURNAME_PERSON_MEDORG).send_keys(self.surname)
        # self.browser.find_element(*PatientCardLocators.REFERRAL_NO).send_keys(self.numbers5)
        # self.browser.find_element(*PatientCardLocators.BLOOD_SAMPLING_DATE).send_keys(self.today)
        # self.browser.find_element(*PatientCardLocators.RECEIPT_DATE).send_keys(self.today)
        # self.browser.find_element(*PatientCardLocators.PRODUCTION_DATE).send_keys(self.today)
        # serum_num_choice = random.choice(['1', '2', '3', '4', '5', '6', '7', '8', '9'])
        # self.browser.execute_script(f"{PatientCardLocators.SERUM_NUM}.dropdown('set selected', '{serum_num_choice}');")
        # self.browser.find_element(*PatientCardLocators.SERUM_NUM2).send_keys(self.numbers5)
        # test_sys_choice = random.choice(['1', '2', '3', '4', '5', '6', '7', '8', '9'])
        # self.browser.execute_script(f"{PatientCardLocators.TEST_SYSTEM_TYPE}.dropdown('set selected', '{test_sys_choice}');")
        # self.browser.find_element(*PatientCardLocators.EXPIRATION_DATE).send_keys(self.expiration_date)
        # self.browser.find_element(*PatientCardLocators.SERIES_NUM).send_keys(self.numbers3)
        # test_cat_choice = random.choice(['1', '2', '0'])
        # self.browser.execute_script(f"{PatientCardLocators.TEST_CATEGORY}.dropdown('set selected', '{test_cat_choice}');")
        # self.browser.find_element(*PatientCardLocators.OP_CRITICAL).send_keys(1)
        # self.browser.find_element(*PatientCardLocators.OP_SERUM).send_keys(2)
        # ifa_res_choice = random.choice(['1', '2', '3', '4'])
        # self.browser.execute_script(f"{PatientCardLocators.IFA_RESULT}.dropdown('set selected', '{ifa_res_choice}');")
        # respon_person_choice = random.choice(['170000000037', '170000000039', '170000000044', '170000000046', '170000000063', '170000000078'])
        # self.browser.execute_script(f"{PatientCardLocators.RESPONSIBLE_PERSON}.dropdown('set selected', '{ respon_person_choice}');")
        # ifa_services_choice = random.choice(['233', '177'])
        # self.browser.execute_script(f"{PatientCardLocators.IFA_SERVICES}.dropdown('set selected', '{ifa_services_choice}');")
        # self.browser.find_element(*PatientCardLocators.IFA_OGC_SAVE).click()
        # sleep(2)
        #
        # self.browser.execute_script(f"{PatientCardLocators.USER_NAME}.click()")
        # self.browser.execute_script(f"$('div[data-name=account-settings] div.menu').children()[0].click()")
        # self.browser.execute_script(f"{PatientCardLocators.PROFILE_EDIT}.click()")
        # self.browser.execute_script(f"{PatientCardLocators.MED_ORG}.dropdown('set selected', '1');")
        # # self.browser.execute_script(f"{PatientCardLocators.MED_ORG}.dropdown('set selected', '29');")
        # self.browser.execute_script(f"{WorkJournalLocators.HOME_ICON}.click()")
        # self.browser.find_element(*WorkJournalLocators.NOTE_CODE).send_keys(patient_id_child)
        # self.browser.execute_script(f"{WorkJournalLocators.FILTER_BTN}.dropdown('set selected', '/visits/patient_card/{patient_id_child}?new=1&in_rk=1');")
        #
        # self.browser.execute_script(f"{PatientCardLocators.OPEN_PATIENT_MENU}.sidebar('show')")  # Развернули карту пациента
        # sleep(1)
        # self.browser.execute_script(f"{PatientCardLocators.LAB_RESEARCH}.click()")  # Открываем Эпидемиологический анамнез
        # sleep(2)
        # self.browser.execute_script(f"{PatientCardLocators.IB_PCR}.click()")
        # self.browser.execute_script(f"{PatientCardLocators.IB_NUMBER}.val('{self.numbers5}');")
        # self.browser.execute_script(f"{PatientCardLocators.IB_SERUM_NUM}.val('{self.numbers4}');")
        # self.browser.execute_script(f"{PatientCardLocators.SAMPLE_NUM}.val('{self.numbers3}');")
        # self.browser.execute_script(f"{PatientCardLocators.IB_RECEIPT_DATE}.calendar('set date', '{self.today}');")
        # self.browser.execute_script(f"{PatientCardLocators.IB_REGISTER_DATE}.calendar('set date', '{self.today}');")
        # self.browser.execute_script(f"{PatientCardLocators.IB_RESULT}.dropdown('set selected', '1');")
        # test_name_choice = random.choice(['1', '2', '3', '64'])
        # self.browser.execute_script(f"{PatientCardLocators.TEST_SYSTEM_NAME}.dropdown('set selected', '{test_name_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.IB_EXPIRATION_DATE}.val('{self.expiration_date}');")
        # self.browser.execute_script(f"{PatientCardLocators.IB_SERIES_NUM}.val('{self.numbers3}');")
        # ib_res_choice = random.choice(['10000000005', '10000000011', '10000000011', '10000000023'])
        # self.browser.execute_script(f"{PatientCardLocators.IB_RESPONSIBLE_PERSON}.dropdown('set selected', '{ib_res_choice}');")
        # gp160 = random.choice(['1', '2', '3'])
        # self.browser.execute_script(f"{PatientCardLocators.GP160}.dropdown('set selected', '{gp160}');")
        # gp110_120 = random.choice(['1', '2', '3'])
        # self.browser.execute_script(f"{PatientCardLocators.GP110_120}.dropdown('set selected', '{gp110_120}');")
        # p68 = random.choice(['1', '2', '3'])
        # self.browser.execute_script(f"{PatientCardLocators.P68}.dropdown('set selected', '{p68}');")
        # p55 = random.choice(['1', '2', '3'])
        # self.browser.execute_script(f"{PatientCardLocators.P55}.dropdown('set selected', '{p55}');")
        # p52 = random.choice(['1', '2', '3'])
        # self.browser.execute_script(f"{PatientCardLocators.P52}.dropdown('set selected', '{p52}');")
        # gp41 = random.choice(['1', '2', '3'])
        # self.browser.execute_script(f"{PatientCardLocators.GP41}.dropdown('set selected', '{gp41}');")
        # p40 = random.choice(['1', '2', '3'])
        # self.browser.execute_script(f"{PatientCardLocators.P40}.dropdown('set selected', '{p40}');")
        # p34 = random.choice(['1', '2', '3'])
        # self.browser.execute_script(f"{PatientCardLocators.P34}.dropdown('set selected', '{p34}');")
        # p25 = random.choice(['1', '2', '3'])
        # self.browser.execute_script(f"{PatientCardLocators.P25}.dropdown('set selected', '{p25}');")
        # p18 = random.choice(['1', '2', '3'])
        # self.browser.execute_script(f"{PatientCardLocators.P18}.dropdown('set selected', '{p18}');")
        # self.browser.execute_script(f"{PatientCardLocators.IB_SERVICES}.dropdown('set selected', '{234}');")
        # self.browser.execute_script(f"{PatientCardLocators.IB_SAVE}.click()")
        # sleep(2)
        #
        # self.browser.find_element(*PatientCardLocators.RESULT).click()
        # self.browser.find_element(*PatientCardLocators.RESULT_ADD).click()
        # self.browser.find_element(*PatientCardLocators.RESULT_NUM).send_keys(self.numbers5)
        # self.browser.find_element(*PatientCardLocators.RESULT_DATE).send_keys(self.today)
        # result_person_choice = random.choice(['170000000044', '170000000080', '170000000092', '170000000098', '170000000034', '170000000039'])
        # self.browser.execute_script(f"{PatientCardLocators.RESULT_RESPONSIBLE_PERSON}.dropdown('set selected', '{result_person_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.LAB_SUPERVISER}.dropdown('set selected', '{result_person_choice}');")
        # result_choice = random.choice(['7', '9', '12', '14', '19'])
        # self.browser.execute_script(f"{PatientCardLocators.ANALYSIS_RESULT}.dropdown('set selected', '{result_choice}');")
        # self.browser.find_element(*PatientCardLocators.RESEARCH_BAZIS).click()
        # self.browser.find_element(*PatientCardLocators.RESULT_SAVE).click()
        # sleep(2)

        self.browser.execute_script(f"{PatientCardLocators.OPEN_PATIENT_MENU}.sidebar('show')")  # Развернули карту пациента
        sleep(1)
        self.browser.execute_script(f"{PatientCardLocators.EPID_HISTORY}.click()")  # Открываем Эпидемиологический анамнез
        sleep(2)
        self.browser.execute_script(f"{PatientCardLocators.EPID_HISTORY_HIV_ANALYSIS}.dropdown('set selected', '1');")
        sleep(1)
        self.browser.execute_script(f"{PatientCardLocators.EPID_HISTORY_ANALYSIS_YEAR}.dropdown('set selected', '2021');")
        sleep(1)
        self.browser.execute_script(f"{PatientCardLocators.EPID_HISTORY_ANALYSIS_RESULT}.dropdown('set selected', '2');")
        self.browser.find_element(*PatientCardLocators.FAMILY_MEM_ADD).click()
        self.browser.find_element(*PatientCardLocators.FAMILY_MEM_LASTNAME).send_keys(self.surname)
        self.browser.find_element(*PatientCardLocators.FAMILY_MEM_NAME).send_keys(self.name)
        self.browser.find_element(*PatientCardLocators.FAMILY_MEM_MIDDLE_NAME).send_keys(self.midname)
        self.browser.execute_script(f"{PatientCardLocators.FAMILY_MEM_GENDER}.dropdown('set selected', '{self.gen_choice1}');")
        self.browser.execute_script(f"$('#fam_members_birth_modal').val('{self.birthday}')")
        self.browser.find_element(*PatientCardLocators.FAMILY_MEM_ADDRESS).send_keys(self.street_choice)
        self.browser.execute_script(f"{PatientCardLocators.FAMILY_MEM_HIV_STATUS}.dropdown('set selected', '1');")
        self.browser.find_element(*PatientCardLocators.FAMILY_MEM_SAVE).click()
        fam_mem_rel_choice = random.choice(['10', '9', '11'])
        self.browser.execute_script(f"{PatientCardLocators.FAMILY_MEM_RELATION}.dropdown('set selected', '{fam_mem_rel_choice}');")
        self.browser.find_element(*PatientCardLocators.FAMILY_MEM_SAVE).click()
        self.browser.find_element(*PatientCardLocators.EPID_HISTORY_FILLING_DATE).send_keys(self.today)
        epid_doc_choice = random.choice(['АСЫЛХАНОВА А. М.', 'АЙДАРХАНОВА А. Ы.', 'ХАСЕНОВА Г. Ж.', 'ЖУМАТАЕВА М. Б.'])
        self.browser.execute_script(f"{PatientCardLocators.EPID_DOCTOR}.dropdown('set selected', '{epid_doc_choice}');")
        sleep(2)

        self.browser.execute_script(f"{PatientCardLocators.LUIN_RS}.click();")
        self.browser.execute_script(f"{PatientCardLocators.DRUG_EXPERIENCE}.dropdown('set selected', '1');")
        self.browser.execute_script(f"{PatientCardLocators.DRUG_USE_IN_TWELVE_MONTH}.dropdown('set selected', '1');")
        self.browser.execute_script(f"{PatientCardLocators.DRUG_USE_YEARS}.val('{self.years_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.DRUG_USE_MONTH}.val('{self.month_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.SHARING_DRUG_INJECTION}.dropdown('set selected', '1');")
        self.browser.execute_script(f"{PatientCardLocators.SHARING_DRUG_INJ_WITH_HIV}.dropdown('set selected', '1');")
        self.browser.execute_script(f"{PatientCardLocators.SHARING_DRUG_INJ_WITH_SEXUAL_PARTNER}.click();")
        self.browser.execute_script(f"{PatientCardLocators.SHARING_DRUG_INJ_WITH_PERMANENT_GROUP}.click();")
        self.browser.execute_script(f"{PatientCardLocators.SHARING_DRUG_INJ_WITH_RANDOM_GROUP}.click();")
        self.browser.execute_script(f"{PatientCardLocators.HERAIN}.click();")
        self.browser.execute_script(f"{PatientCardLocators.HANKA}.click();")
        self.browser.execute_script(f"{PatientCardLocators.MAK}.click();")
        self.browser.execute_script(f"{PatientCardLocators.AMPHETAMIN}.click();")
        self.browser.execute_script(f"{PatientCardLocators.SINTETHICS}.click();")
        self.browser.execute_script(f"{PatientCardLocators.OTHER_DRUGS}.click();")
        self.browser.execute_script(f"{PatientCardLocators.ACCOUNTED_IN_NARCO_DISP}.dropdown('set selected', '1');")
        self.browser.execute_script(f"{PatientCardLocators.ACCOUNTED_IN_POLICE_FILES}.dropdown('set selected', '1');")
        self.browser.execute_script(f"{PatientCardLocators.COMMERCIAL_SEX_EXP}.dropdown('set selected', '1');")
        self.browser.execute_script(f"{PatientCardLocators.COMMERCIAL_SEX_EXP_YEARS}.val('{self.years_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.COMMERCIAL_SEX_EXP_MONTH}.val('{self.month_choice}');")
        com_sex_partners_choice = random.choice(['10', '20', '30', '14', '25', '36', '27', '18', '39', '17'])
        self.browser.execute_script(f"{PatientCardLocators.COMMERCIAL_SEX_PARTNER_NUM}.val('{com_sex_partners_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.CONDOM_USAGE}.dropdown('set selected', '1');")
        self.browser.find_element(*PatientCardLocators.LUIN_RS_SAVE).click()

        self.browser.execute_script(f"{PatientCardLocators.SEXUAL_CONTACTS}.click();")
        sleep(2)
        self.browser.execute_script(f"{PatientCardLocators.HOMO_EXPIRIENCE}.dropdown('set selected', '1');")
        sleep(1)
        self.browser.execute_script(f"{PatientCardLocators.HOMO_EXP_YEAR}.dropdown('set selected', '1');")
        homo_sex_partners_choice = random.choice(['20', '30', '24', '25', '36', '27', '18', '39', '17'])
        self.browser.execute_script(f"{PatientCardLocators.HOMO_SEX_PARTNER_NUM}.val('{homo_sex_partners_choice}');")
        sex_partners_year_choice = random.choice(['10', '11', '12', '14', '13', '15', '16', '9', '17'])
        self.browser.execute_script(f"{PatientCardLocators.HOMO_SEX_PARTNER_NUM_YEAR}.val('{sex_partners_year_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.COMMERCIAL_HOMO_SEX_PARTNER_YEAR}.dropdown('set selected', '1');")
        self.browser.execute_script(f"{PatientCardLocators.HOMO_SEX_WITH_HIV}.dropdown('set selected', '1');")
        self.browser.execute_script(f"{PatientCardLocators.HOMO_SEX_WITH_LUIN}.dropdown('set selected', '1');")
        self.browser.execute_script(f"{PatientCardLocators.DRUG_EXPERIENCE}.dropdown('set selected', '1');")
        self.browser.execute_script(f"{PatientCardLocators.HOMO_PERMANENT_SEX_PARTNERS}.click();")
        self.browser.execute_script(f"{PatientCardLocators.HOMO_RANDOM_SEX_PARTNERS}.click();")
        self.browser.execute_script(f"{PatientCardLocators.COMMERCIAL_HOMO_SEX_PARTNERS}.click();")
        self.browser.execute_script(f"{PatientCardLocators.HOMO_PERMANENT_SEX_PARTNERS_YEAR}.click();")
        self.browser.execute_script(f"{PatientCardLocators.HOMO_RANDOM_SEX_PARTNERS_YEAR}.click();")
        self.browser.execute_script(f"{PatientCardLocators.COMMERCIAL_HOMO_SEX_PARTNERS_YEAR}.click();")
        sleep(1)
        self.browser.execute_script(f"{PatientCardLocators.HETERO_EXPIRIENCE}.dropdown('set selected', '1');")
        sleep(1)
        self.browser.execute_script(f"{PatientCardLocators.COMMERCIAL_HET_SEX_PARTNER}.dropdown('set selected', '1');")
        self.browser.execute_script(f"{PatientCardLocators.HET_SEX_WITH_HIV}.dropdown('set selected', '1');")
        self.browser.execute_script(f"{PatientCardLocators.HET_SEX_WITH_LUIN}.dropdown('set selected', '1');")
        self.browser.execute_script(f"{PatientCardLocators.HET_SEX_EXP_YEAR}.dropdown('set selected', '1');")
        self.browser.execute_script(f"{PatientCardLocators.HET_SEX_PARTNER_NUM_YEAR}.val('{sex_partners_year_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.HET_PERMANENT_SEX_PARTNERS_YEAR}.click();")
        self.browser.execute_script(f"{PatientCardLocators.HET_RANDOM_SEX_PARTNERS_YEAR}.click();")
        self.browser.execute_script(f"{PatientCardLocators.COMMERCIAL_HET_SEX_PARTNERS_YEAR}.click();")
        self.browser.execute_script(f"{PatientCardLocators.HET_PERMANENT_SEX_PARTNERS_LIVE}.click();")
        self.browser.execute_script(f"{PatientCardLocators.HET_RANDOM_SEX_PARTNERS_LIVE}.click();")
        self.browser.execute_script(f"{PatientCardLocators.COMMERCIAL_HET_SEX_PARTNERS_LIVE}.click();")
        sleep(1)
        self.browser.find_element(*PatientCardLocators.SEXUAL_CONTACTS_SAVE).click()

        self.browser.execute_script(f"{PatientCardLocators.MLS}.click();")
        self.browser.execute_script(f"{PatientCardLocators.MLS_EXPERIENCE}.click();")
        self.browser.execute_script(f"{PatientCardLocators.MLS_ADD}.click();")
        deduction_choice = random.choice(['7', '9', '12', '14', '19', '10', '20', '30', '14', '25', '36', '27', '18', '39', '17'])
        self.browser.execute_script(f"{PatientCardLocators.MLS_NAME}.dropdown('set selected', '{deduction_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.MLS_DATE_START}.val('01.01.2017');")
        self.browser.execute_script(f"{PatientCardLocators.MLS_DATE_END}.val('01.01.2020');")
        self.browser.execute_script(f"{PatientCardLocators.MLS_SAVE}.click();")

        self.browser.execute_script(f"{PatientCardLocators.DONOR}.click();")
        self.browser.execute_script(f"{PatientCardLocators.BLOOD_DONOR}.click();")
        self.browser.execute_script(f"{PatientCardLocators.DONATION_EXISTENCE}.click();")
        self.browser.execute_script(f"{PatientCardLocators.BLOOD_DONOR_ADD}.click();")
        self.browser.execute_script(f"{PatientCardLocators.BLOOD_DONATION_PLACE}.dropdown('set selected', '1');")
        self.browser.execute_script(f"{PatientCardLocators.BLOOD_DONATION_AREA}.dropdown('set selected', '3');")
        self.browser.execute_script(f"{PatientCardLocators.BLOOD_DONATION_UNIT_AREA}.dropdown('set selected', '33');")
        self.browser.execute_script(f"{PatientCardLocators.BLOOD_DONATION_LOCALITY}.dropdown('set selected', '{self.locality_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.BLOOD_DONATION_DATE}.val('01.01.2021');")
        self.browser.execute_script(f"{PatientCardLocators.BLOOD_DONATION_MED_ORG}.dropdown('set selected', '{self.mo_choice}');")
        blood_don_cat_choice = random.choice(['1', '2', '3'])
        self.browser.execute_script(f"{PatientCardLocators.BLOOD_DONOR_CATEGORY}.dropdown('set selected', '{blood_don_cat_choice}');")
        blood_don_type_choice = random.choice(['1', '2'])
        self.browser.execute_script(f"{PatientCardLocators.BLOOD_DONOR_TYPE}.dropdown('set selected', '{blood_don_type_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.BLOOD_DONOR_CODE}.val('{self.numbers3}');")
        self.browser.execute_script(f"{PatientCardLocators.BLOOD_DONATION_CODE}.val('{self.numbers4}');")
        self.browser.execute_script(f"{PatientCardLocators.BLOOD_HIV_ANALYSIS_DATE}.val('01.01.2021');")
        self.browser.execute_script(f"{PatientCardLocators.BLOOD_HIV_STATUS}.dropdown('set selected', '1');")
        self.browser.execute_script(f"{PatientCardLocators.BLOOD_DONOR_SAVE}.click();")
        self.browser.execute_script(f"{PatientCardLocators.ORGAN_DONOR}.click();")
        self.browser.execute_script(f"{PatientCardLocators.ORGAN_DONOR_ADD}.click();")
        self.browser.execute_script(f"{PatientCardLocators.ORGAN_DONATION_PLACE}.dropdown('set selected', '1');")
        self.browser.execute_script(f"{PatientCardLocators.ORGAN_DONATION_AREA}.dropdown('set selected', '3');")
        self.browser.execute_script(f"{PatientCardLocators.ORGAN_DONATION_UNIT_AREA}.dropdown('set selected', '33');")
        self.browser.execute_script(f"{PatientCardLocators.ORGAN_DONATION_LOCALITY}.dropdown('set selected', '{self.locality_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.ORGAN_DONATION_DATE}.val('01.01.2021');")
        self.browser.execute_script(f"{PatientCardLocators.ORGAN_DONOR_MED_ORG}.dropdown('set selected', '{self.mo_choice}');")
        organ_don_cat_choice = random.choice(['1', '2', '3'])
        self.browser.execute_script(f"{PatientCardLocators.ORGAN_DONATION_CATEGORY}.dropdown('set selected', '{organ_don_cat_choice}');")
        organ_don_type_choice = random.choice(['1', '2'])
        self.browser.execute_script(f"{PatientCardLocators.ORGAN_DONOR_TYPE}.dropdown('set selected', '{organ_don_type_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.ORGAN_DONOR_MAT_TYPE}.dropdown('set selected', '{self.organ_mat_type_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.ORGAN_DONOR_MAT_NO}.val('{self.numbers3}');")
        self.browser.execute_script(f"{PatientCardLocators.ORGAN_RECIPIENT_MED_ORG}.dropdown('set selected', '{self.mo_rec_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.ORGAN_HIV_ANALYSIS_DATE}.val('01.01.2021');")
        self.browser.execute_script(f"{PatientCardLocators.ORGAN_HIV_STATUS}.dropdown('set selected', '1');")
        self.browser.execute_script(f"{PatientCardLocators.ORGAN_DONOR_SAVE}.click();")

        self.browser.execute_script(f"{PatientCardLocators.RECIPIENT}.click();")
        self.browser.execute_script(f"{PatientCardLocators.BLOOD_RECIPIENT}.click();")
        self.browser.execute_script(f"{PatientCardLocators.BLOOD_RECIPIENT_ADD}.click();")
        self.browser.execute_script(f"{PatientCardLocators.TRANSFUSION_PLACE}.dropdown('set selected', '1');")
        self.browser.execute_script(f"{PatientCardLocators.BLOOD_TRANSFUSION_AREA}.dropdown('set selected', '3');")
        self.browser.execute_script(f"{PatientCardLocators.BLOOD_TRANSFUSION_UNIT_AREA}.dropdown('set selected', '33');")
        self.browser.execute_script(f"{PatientCardLocators.BLOOD_TRANSFUSION_LOCALITY}.dropdown('set selected', '{self.locality_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.BLOOD_TRANSFUSION_DATE}.val('01.01.2021');")
        self.browser.execute_script(f"{PatientCardLocators.BLOOD_TRANSFUSION_MED_ORG}.dropdown('set selected', '{self.mo_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.EPID_HISTORY_NUM_REC}.val('{self.numbers5}');")
        self.browser.execute_script(f"{PatientCardLocators.BLOOD_DONOR_CODE_REC}.val('{self.numbers3}');")
        self.browser.execute_script(f"{PatientCardLocators.BLOOD_COMPONENT_CODE_REC}.val('{self.numbers4}');")
        self.browser.execute_script(f"{PatientCardLocators.BLOOD_HIV_STATUS_REC}.dropdown('set selected', '1');")
        self.browser.execute_script(f"{PatientCardLocators.BLOOD_RECEIPT_SAVE}.click();")

        self.browser.execute_script(f"{PatientCardLocators.ORGAN_RECIPIENT}.click();")
        self.browser.execute_script(f"{PatientCardLocators.ORGAN_RECIPIENT_ADD}.click();")
        self.browser.execute_script(f"{PatientCardLocators.ORGAN_TRANSFUSION_PLACE}.dropdown('set selected', '1');")
        self.browser.execute_script(f"{PatientCardLocators.ORGAN_TRANSFUSION_AREA}.dropdown('set selected', '3');")
        self.browser.execute_script(f"{PatientCardLocators.ORGAN_TRANSFUSION_UNIT_AREA}.dropdown('set selected', '33');")
        self.browser.execute_script(f"{PatientCardLocators.ORGAN_TRANSFUSION_LOCALITY}.dropdown('set selected', '{self.locality_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.ORGAN_DONOR_MED_ORG_REC}.dropdown('set selected', '{self.mo_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.ORGAN_RECEIPT_MED_ORG}.dropdown('set selected', '{self.mo_rec_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.ORGAN_TRANSFUSION_DATE}.val('01.01.2021');")
        self.browser.execute_script(f"{PatientCardLocators.ORGAN_DONOR_MAT_NO_REC}.val('{self.numbers3}');")
        self.browser.execute_script(f"{PatientCardLocators.ORGAN_DONOR_MAT_TYPE_REC}.dropdown('set selected', '{self.organ_mat_type_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.ORGAN_DONOR_NAME}.val('01.01.2021');")
        self.browser.execute_script(f"{PatientCardLocators.ORGAN_HIV_STATUS_REC}.dropdown('set selected', '1');")
        self.browser.execute_script(f"{PatientCardLocators.ORGAN_RECEIPT_SAVE}.click();")

        self.browser.execute_script(f"{PatientCardLocators.IPPP}.click();")
        self.browser.execute_script(f"{PatientCardLocators.IPPP_SYMPTOM_EXISTENCE}.dropdown('set selected', '1');")
        self.browser.execute_script(f"{PatientCardLocators.DISP_ACCOUNTED_KVD}.dropdown('set selected', '1');")
        self.browser.execute_script(f"{PatientCardLocators.DK_CONTACTING}.dropdown('set selected', '1');")
        self.browser.execute_script(f"{PatientCardLocators.DK_CONTACTING_NUM_YEAR}.val('{self.contacting_num}');")
        self.browser.execute_script(f"{PatientCardLocators.PRIVATE_CLINICS_CONTACTING}.dropdown('set selected', '1');")
        self.browser.execute_script(f"{PatientCardLocators.PRIVATE_CLINICS_CONTACTING_NUM}.val('{self.contacting_num}');")
        self.browser.execute_script(f"{PatientCardLocators.IPPP_SYMPTOM_ADD}.click();")
        self.browser.execute_script(f"{PatientCardLocators.DIAGNOSIS_DATE}.calendar('set date', '{self.diagnosis_date}');")
        self.browser.execute_script(f"{PatientCardLocators.DIAGNOSIS}.val('{self.smth_random}');")
        self.browser.execute_script(f"{PatientCardLocators.IPPP_SYMPTOM_SAVE}.click();")
        sleep(2)
        c_section_choice = random.choice(['1', '2'])
        self.browser.execute_script(f"{PatientCardLocators.C_SECTION_DELIVERY}.dropdown('set selected', '{c_section_choice}');")
        mat_chem_choice = random.choice(['1', '2', '3'])
        self.browser.execute_script(f"{PatientCardLocators.MATERNAL_CHEMOPROPHYLAXIS}.dropdown('set selected', '{mat_chem_choice}');")
        feeding_choice = random.choice(['1', '2', '3'])
        self.browser.execute_script(f"{PatientCardLocators.ARTIFICIAL_FEEDING}.dropdown('set selected', '{feeding_choice}');")
        # child_chem_choice = random.choice(['1', '2', '3'])
        # self.browser.execute_script(f"{PatientCardLocators.CHILD_CHEMOPROPHYLAXIS}.dropdown('set selected', '{child_chem_choice}');")

        self.browser.execute_script(f"{PatientCardLocators.MANIPULATIONS_EMERGENCIES}.click();")
        self.browser.execute_script(f"{PatientCardLocators.MANIPULATION_EXISTENCE}.click();")
        self.browser.execute_script(f"{PatientCardLocators.MANIPULATIONS_ADD}.click();")
        self.browser.execute_script(f"{PatientCardLocators.MANIPULATIONS_DATE}.calendar('set date', '{self.manip_emerg_date}');")
        manip_sort_choice = random.choice(['1', '2'])
        self.browser.execute_script(f"{PatientCardLocators.MANIPULATIONS_SORT}.dropdown('set selected', '{manip_sort_choice}');")
        manip_type_choice = random.choice(['1', '2', '3', '4', '5', '6', '7', '8', '10', '9', '11'])
        self.browser.execute_script(f"{PatientCardLocators.MANIPULATIONS_TYPE}.dropdown('set selected', '{manip_type_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.MANIPULATIONS_MED_ORG}.dropdown('set selected', '{self.mo_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.MANIPULATIONS_SAVE}.click();")
        sleep(2)

        self.browser.execute_script(f"{PatientCardLocators.EMERGENCIES}.click();")
        self.browser.execute_script(f"{PatientCardLocators.EMERGENCIES_ADD}.click();")
        self.browser.execute_script(f"{PatientCardLocators.EMERGENCIES_DATE}.calendar('set date', '{self.manip_emerg_date}');")
        infection_choice = random.choice(['1', '2'])
        self.browser.execute_script(f"{PatientCardLocators.INFECTION_RISK}.dropdown('set selected', '{infection_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.EMERGENCIES_MED_ORG}.val('Pupkin cliniс');")
        trauma_choice = random.choice(['1', '2', '3', '4', '5'])
        self.browser.execute_script(f"{PatientCardLocators.TRAUMA_TYPE}.dropdown('set selected', '{trauma_choice}');")
        hours72_choice = random.choice(['1', '2', '3'])
        self.browser.execute_script(f"{PatientCardLocators.EMERGENCIES_72HOURS}.dropdown('set selected', '{hours72_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.EMERGENCIES_HIV_STATUS}.dropdown('set selected', '1');")
        self.browser.execute_script(f"{PatientCardLocators.EMERGENCIES_SAVE}.click();")

        self.browser.execute_script(f"{PatientCardLocators.DEPARTURES_SOURCES}.click();")
        self.browser.execute_script(f"{PatientCardLocators.DEPARTURE_EXISTENCE}.click();")
        self.browser.execute_script(f"{PatientCardLocators.DEPARTURE_ADD}.click();")
        self.browser.execute_script(f"{PatientCardLocators.DEPARTURE_DATE_START}.calendar('set date', '{self.eighty_days_ago}');")
        self.browser.execute_script(f"{PatientCardLocators.DEPARTURE_DATE_END}.calendar('set date', '{self.sixty_days_ago}');")
        self.browser.execute_script(f"{PatientCardLocators.DEPARTURE_COUNTRY}.dropdown('set selected', '{self.country_choice}');")
        purpose_choice = random.choice(['1', '2', '3', '4', '5', '6'])
        self.browser.execute_script(f"{PatientCardLocators.DEPARTURE_PURPOSE}.dropdown('set selected', '{purpose_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.DEPARTURE_SAVE}.click();")

        self.browser.execute_script(f"{PatientCardLocators.INFECTION_SOURCE_EXISTENCE}.click();")
        self.browser.execute_script(f"{PatientCardLocators.SOURCE_ADD}.click();")
        self.browser.execute_script(f"{PatientCardLocators.SOURCE_IB_NUM}.val('{self.numbers4}');")
        self.browser.execute_script(f"{PatientCardLocators.SOURCE_IB_DATE}.calendar('set date', '{self.ib_date}');")
        self.browser.execute_script(f"{PatientCardLocators.SOURCE_SURNAME}.val('{self.surname}');")
        self.browser.execute_script(f"{PatientCardLocators.SOURCE_NAME}.val('{self.name}');")
        self.browser.execute_script(f"{PatientCardLocators.SOURCE_MIDDLE_NAME}.val('{self.midname}');")
        self.browser.execute_script(f"{PatientCardLocators.SOURCE_SAVE}.click();")

        self.browser.execute_script(f"{PatientCardLocators.CONTACT_PERSON}.click();")
        self.browser.execute_script(f"{PatientCardLocators.CONTACT_PERSON_EXISTENCE}.click();")
        self.browser.execute_script(f"{PatientCardLocators.CONTACT_PERSON_ADD}.click();")
        self.browser.execute_script(f"{PatientCardLocators.CONTACT_PERSON_SURNAME}.val('{self.surname}');")
        self.browser.execute_script(f"{PatientCardLocators.CONTACT_PERSON_NAME}.val('{self.name}');")
        self.browser.execute_script(f"{PatientCardLocators.CONTACT_PERSON_MIDDLE_NAME}.val('{self.midname}');")
        self.browser.execute_script(f"{PatientCardLocators.CONTACT_PERSON_GENDER}.dropdown('set selected', '{self.gen_choice1}');")
        self.browser.execute_script(f"{PatientCardLocators.CONTACT_PERSON_BIRTHDAY}.val('{self.birthday}');")
        self.browser.execute_script(f"{PatientCardLocators.CONTACT_DATE_START}.val('{self.fifty_days_ago}');")
        contact_type_choice = random.choice(['1', '2', '3', '4', '5', '6', '7'])
        self.browser.execute_script(f"{PatientCardLocators.CONTACT_TYPE}.dropdown('set selected', '{contact_type_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.CONTACT_IB_NUM}.val('{self.numbers4}');")
        self.browser.execute_script(f"{PatientCardLocators.CONTACT_IB_NUM_DATE}.val('{self.ib_date}');")
        self.browser.execute_script(f"{PatientCardLocators.CONTACT_SURVEY_ADD}.click();")
        self.browser.execute_script(f"{PatientCardLocators.CONTACT_DIAGNOSTICS_DATE}.calendar('set date', '{self.diagnosis_date}');")
        contact_hiv_choice = random.choice(['1', '2', '3'])
        self.browser.execute_script(f"{PatientCardLocators.CONTACT_HIV_STATUS}.dropdown('set selected', '{contact_hiv_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.CONTACT_SURVEY_SAVE}.click();")
        contact_hiv_status = self.browser.execute_script(f"$('#obsled_state').attr('data-field')")
        if contact_hiv_status == "3":
            con_reason_not_surv_choice = random.choice(['1', '2', '3', '4', '5', '6', '7'])
            self.browser.execute_script(f"{PatientCardLocators.REASON_NOT_SURVEYING}.dropdown('set selected', '{con_reason_not_surv_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.CONTACT_FINISHED}.click();")
        self.browser.execute_script(f"{PatientCardLocators.CONTACT_DAY_END}.val('{self.twenty_days_ago}');")
        self.browser.execute_script(f"{PatientCardLocators.CONTACT_AREA}.dropdown('set selected', '3');")
        self.browser.execute_script(f"{PatientCardLocators.CONTACT_UNIT_AREA}.click();")
        self.browser.execute_script(f"{PatientCardLocators.CONTACT_UNIT_AREA}.dropdown('set selected', '33');")
        self.browser.execute_script(f"{PatientCardLocators.CONTACT_UNIT_AREA}.dropdown('hide');")
        # self.browser.execute_script(f"{PatientCardLocators.CONTACT_UNIT_AREA}.dropdown('set selected', '33');")
        self.browser.execute_script(f"{PatientCardLocators.CONTACT_LOCALITY}.dropdown('set selected', '{self.locality_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.CONTACT_STREET}.val('{self.street_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.CONTACT_HOUSE}.val('55');")
        self.browser.execute_script(f"{PatientCardLocators.CONTACT_APT}.val('47');")
        self.browser.execute_script(f"{PatientCardLocators.CONTACT_PHONE_NO}.val('87279876543');")
        self.browser.execute_script(f"{PatientCardLocators.CONTACT_PERSON_SAVE}.click();")
        sleep(2)

        self.browser.execute_script(f"{PatientCardLocators.OPEN_PATIENT_MENU}.sidebar('show')")  # Развернули карту пациента
        sleep(1)
        self.browser.execute_script(f"{PatientCardLocators.DISP_OBSERVATION}.click();")
        sleep(2)
        # self.browser.execute_script(f"{PatientCardLocators.DISP_OBSER_ADD}.click();")
        # # self.browser.execute_script(f"{PatientCardLocators.D_OBSER_AIDC_CENTER}.dropdown('set selected', '{mo_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.DATE_OF_REGIS}.calendar('set date', '{self.regis_date}');")
        # self.browser.execute_script(f"{PatientCardLocators.DATE_OF_DEREGIS}.calendar('set date', '{self.deregis_date}');")
        # reason_deregis_choice = random.choice(['1', '2', '3', '4', '8', '9', '10'])
        # self.browser.execute_script(f"{PatientCardLocators.D_OBSER_REASON_OF_DEREGIS}.dropdown('set selected', '{reason_deregis_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.D_OBSER_COUNTRY}.dropdown('set selected', '{self.country_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.D_OBSER_AREA}.dropdown('set selected', '3');")
        # sleep(1)
        # self.browser.execute_script(f"{PatientCardLocators.D_OBSER_UNIT_AREA_CLICK}.focus();")
        # sleep(1)
        # self.browser.execute_script(f"{PatientCardLocators.D_OBSER_UNIT_AREA_CLICK}.click();")
        # sleep(1)
        # self.browser.execute_script(f"{PatientCardLocators.D_OBSER_UNIT_AREA}.dropdown('set selected', '33');")
        # sleep(1)
        # self.browser.execute_script(f"{PatientCardLocators.D_OBSER_UNIT_AREA}.dropdown('hide');")
        # self.browser.execute_script(f"{PatientCardLocators.D_OBSER_UNIT_AREA}.dropdown('set selected', '33');")
        # if reason_deregis_choice == 1:
        #     self.browser.execute_script(f"{PatientCardLocators.DATE_OF_DEATH}.calendar('set date', '{self.deregis_date}');")
        #     aidc_death_choice = random.choice(['1', '2'])
        #     self.browser.execute_script(f"{PatientCardLocators.AIDC_RELATED_DEATH}.dropdown('set selected', '{aidc_death_choice}');")
        #     death_choice = random.choice(['1', '2', '13', '4', '17', '18', '12'])
        #     self.browser.execute_script(f"{PatientCardLocators.DEATH_REASON}.dropdown('set selected', '{death_choice}');")
        #     death_place_choice = random.choice(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'])
        #     self.browser.execute_script(f"{PatientCardLocators.DEATH_PLACE}.dropdown('set selected', '{death_place_choice}');")
        #     self.browser.execute_script(f"{PatientCardLocators.AUTOPSY}.click();")
        #     self.browser.execute_script(f"{PatientCardLocators.PATHOLOGOANATOMIC_DIAGNOSIS}.val('Положительный');")
        # sleep(1)
        # self.browser.execute_script("$('#modal_d_uchet_vzyatie .ui.green.approve.button').click();")
        # # self.browser.execute_script(f"{PatientCardLocators.D_OBSER_SAVE}.click();")
        # sleep(3)
        # drug_cons_choice = random.choice(['1', '2'])
        # self.browser.execute_script(f"{PatientCardLocators.DRUG_INJ_CONSUMPTION}.dropdown('set selected', '{drug_cons_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.DRUG_CONSUMPTION_YEAR}.val('2');")
        # drug_regis_choice = random.choice(['1', '2'])
        # self.browser.execute_script(f"{PatientCardLocators.DRUG_CONSUMPTION_REGIS}.dropdown('set selected', '{drug_regis_choice}');")
        # alc_cons_choice = random.choice(['1', '2'])
        # self.browser.execute_script(f"{PatientCardLocators.ALCOHOL_CONSUMPTION}.dropdown('set selected', '{alc_cons_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.OUTPATIENT_CARD_NO}.val('{self.numbers4}');")
        # self.browser.execute_script(f"{PatientCardLocators.DISP_START_DATE}.calendar('set date', '{self.sixty_days_ago}');")
        # disp_doc_choice = random.choice(['АСЫЛХАНОВА АЛИЯ МАНАТОВНА', 'АЙДАРХАНОВА АНАРА ЫНТЫКПАЕВНА', 'ЖАРЫЛГАПОВА Ж Т', 'МУБАРАКОВА У. Н.'])
        # self.browser.execute_script(f"{PatientCardLocators.DISP_DOCTORS_NAME}.dropdown('set selected', '{disp_doc_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.DISP_SAVE_BTN}.click();")
        # sleep(1)
        #
        # self.browser.execute_script(f"{PatientCardLocators.PERINATAL_REGISTRATION}.click();")
        # self.browser.execute_script(f"{PatientCardLocators.PERINATAL_REGIS_ADD}.click();")
        # self.browser.execute_script(f"{PatientCardLocators.PERINATAL_MED_ORG}.dropdown('set selected', '{self.aidc_center_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.PERINATAL_DATE_OF_REGIS}.calendar('set date', '{self.regis_date}');")
        # self.browser.execute_script(f"{PatientCardLocators.PERINATAL_DATE_OF_DEREGIS}.calendar('set date', '{self.deregis_date}');")
        # reason_deregis_choice = random.choice(['1', '2', '3', '4', '5'])
        # self.browser.execute_script(f"{PatientCardLocators.PERINATAL_REASON_OF_DEREGIS}.dropdown('set selected', '{reason_deregis_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.PERINATAL_COUNTRY}.dropdown('set selected', '{self.country_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.PERINATAL_AREA}.dropdown('set selected', '3');")
        # self.browser.execute_script(f"{PatientCardLocators.PERINATAL_UNIT_AREA}.dropdown('set selected', '33');")
        # if reason_deregis_choice == 4:
        #     self.browser.execute_script(f"{PatientCardLocators.PERINATAL_DATE_OF_DEATH}.calendar('set date', '{self.deregis_date}');")
        #     death_choice = random.choice(['1', '2', '13', '4', '17', '18', '12'])
        #     self.browser.execute_script(f"{PatientCardLocators.PERINATAL_DEATH_REASON}.dropdown('set selected', '{death_choice}');")
        #     death_place_choice = random.choice(['1', '2', '3', '4', '5', '6', '7', '8', '9'])
        #     self.browser.execute_script(f"{PatientCardLocators.PERINATAL_DEATH_PLACE}.dropdown('set selected', '{death_place_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.PERINATAL_SAVE}.click();")
        # sleep(1)
        # arv_proph_choice = random.choice(['1', '2'])
        # self.browser.execute_script(f"{PatientCardLocators.ARV_PROPHYLAXIS}.dropdown('set selected', '{arv_proph_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.ARV_START_DATE}.calendar('set date', '{self.eighty_days_ago}');")
        # self.browser.execute_script(f"{PatientCardLocators.ARV_END_DATE}.calendar('set date', '{self.fifty_days_ago}');")
        # reason_deregis_choice = random.choice(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'])
        # self.browser.execute_script(f"{PatientCardLocators.ARV_MEDICATION}.dropdown('set selected', '{reason_deregis_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.ARV_ISSUANCE}.click();")
        # self.browser.execute_script(f"{PatientCardLocators.ARV_ISSUANCE_ADD}.click();")
        # sleep(1)
        # self.browser.execute_script(f"{PatientCardLocators.ARV_MEDICATION_NAME}.click();")
        # sleep(2)
        # self.browser.execute_script(f"{PatientCardLocators.ARV_MEDICATION_NAME_CHOICE}.click();")
        # #self.browser.execute_script(f"$('#add-row-preparaty-table tr:eq(0) td:eq(0) a').click();")
        # sleep(1)
        # self.browser.execute_script(f"{PatientCardLocators.ARV_RECIPE_NUM}.val('{self.numbers4}');")
        # self.browser.execute_script(f"{PatientCardLocators.ARV_DAY_NUM}.val('30');")
        # self.browser.execute_script(f"{PatientCardLocators.ARV_NEXT_DATE}.calendar('set date', '{self.thirty_days_forward}');")
        # self.browser.execute_script(f"{PatientCardLocators.ARV_MEDICATION_SAVE}.click();")
        # sleep(2)
        # self.browser.execute_script(f"{PatientCardLocators.ARV_ISSUANCE_SAVE}.click();")
        # sleep(2)
        # self.browser.execute_script(f"{PatientCardLocators.PCP_PROPHYLAXIS_START_DATE}.calendar('set date', '{self.fifty_days_ago}');")
        # self.browser.execute_script(f"{PatientCardLocators.PCP_PROPHYLAXIS_END_DATE}.calendar('set date', '{self.thirty_days_ago}');")
        # arv_hiv_choice = random.choice(['1', '2', '3'])
        # self.browser.execute_script(f"{PatientCardLocators.ARV_HIV_STATUS}.dropdown('set selected', '{arv_hiv_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.ARV_HIV_DETERMINATION_DATE}.calendar('set date', '{self.fifty_days_ago}');")
        #
        # self.browser.execute_script(f"{PatientCardLocators.HIV_DIAGNOSIS}.click();")
        # self.browser.execute_script(f"{PatientCardLocators.HIV_DIAGNOSIS_ADD}.click();")
        # self.browser.execute_script(f"{PatientCardLocators.FORMULATING_CHANGE_DATE}.calendar('set date', '{self.thirty_days_ago}');")
        # hiv_stage_choice = random.choice(['1', '2', '3', '4'])
        # self.browser.execute_script(f"{PatientCardLocators.HIV_STAGE}.dropdown('set selected', '{hiv_stage_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.HIV_DIAGNOSIS_SAVE}.click();")
        #
        # self.browser.execute_script(f"{PatientCardLocators.HIV_RELATED_DISEASE_ADD}.click();")
        # self.browser.execute_script(f"{PatientCardLocators.RELATED_DISEASE_HIV_STAGE}.click();")
        # self.browser.execute_script(f"{PatientCardLocators.RELATED_DISEASE_HIV_STAGE_CHOICE}.click();")
        # self.browser.execute_script(f"{PatientCardLocators.DISEASE_START_DATE}.val('{self.thirty_days_ago}');")
        # self.browser.execute_script(f"{PatientCardLocators.DISEASE_END_DATE}.val('{self.twenty_days_ago}');")
        # disease_name_choice = random.choice(['1', '2', '3', '4', '5', '6', '7', '8', '33', '27'])
        # self.browser.execute_script(f"{PatientCardLocators.DISEASE_NAME}.dropdown('set selected', '{disease_name_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.HIV_RELATED_DISEASE_SAVE}.click();")
        # sleep(2)
        # self.browser.execute_script(f"{PatientCardLocators.RECOM_CONSULTATION_ADD}.click();")
        # self.browser.execute_script(f"{PatientCardLocators.CONSULTATION_DATE}.calendar('set date', '{self.thirty_days_forward}');")
        # consultation_choice = random.choice(['325', '340', '13', '337', '308', '310', '312'])
        # self.browser.execute_script(f"{PatientCardLocators.CONSULTATION}.dropdown('set selected', '{consultation_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.CONSULTATION_DESCRIPTION}.val('Положительный');")
        # self.browser.execute_script(f"{PatientCardLocators.RECOM_CONSULTATION_SAVE}.click();")
        # sleep(2)
        # self.browser.execute_script(f"{PatientCardLocators.RECOM_SCREENING_ADD}.click();")
        # self.browser.execute_script(f"{PatientCardLocators.SCREENING_DATE}.calendar('set date', '{self.thirty_days_forward}');")
        # survey_choice = random.choice(['325', '339', '13', '337', '308', '310', '312'])
        # self.browser.execute_script(f"{PatientCardLocators.SURVEY}.dropdown('set selected', '{survey_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.SCREENING_DESCRIPTION}.val('Положительный');")
        # self.browser.execute_script(f"{PatientCardLocators.RECOM_SCREENING_SAVE}.click();")
        # self.browser.execute_script(f"{PatientCardLocators.REFERRAL_ADD}.click();")
        # self.browser.execute_script(f"{PatientCardLocators.REFERRAL_DATE}.calendar('set date', '{self.today}');")
        # referral_name_choice = random.choice(['178', '35', '36', '37', '38', '40', '46'])
        # self.browser.execute_script(f"{PatientCardLocators.REFERRAL_NAME}.dropdown('set selected', '{referral_name_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.REFERRAL_NUM}.val('{self.numbers4}');")
        # self.browser.execute_script(f"{PatientCardLocators.SENDER_ORG}.dropdown('set selected', '{self.mo_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.RECIPIENT_ORG}.dropdown('set selected', '{self.mo_choice}');")
        # category_choice = random.choice(['1', '2', '3', '4', '5', '6', '7', '8'])
        # self.browser.execute_script(f"{PatientCardLocators.CATEGORY}.dropdown('set selected', '{category_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.NOSOLOGY}.click();")
        # self.browser.execute_script(f"{PatientCardLocators.NOSOLOGY_CHOICE}.click();")
        # self.browser.execute_script(f"{PatientCardLocators.SURVEY_ELEMENTS}.val('Не знаю');")
        # self.browser.execute_script(f"{PatientCardLocators.SCREENING_RESULT}.val('Положительный');")
        # self.browser.execute_script(f"{PatientCardLocators.REFERRAL_SAVE}.click();")
        #
        # self.browser.execute_script(f"{PatientCardLocators.CD4_VL_SURVEY}.click();")
        # self.browser.execute_script(f"{PatientCardLocators.CD4_DETERMINATION_ADD}.click();")
        # self.browser.execute_script(f"{PatientCardLocators.REGISTRATION_NUM}.val('{self.numbers5}');")
        # self.browser.execute_script(f"{PatientCardLocators.CD4_BLOOD_DONOR_MED_ORG}.dropdown('set selected', '{self.mo_choice1}');")
        # self.browser.execute_script(f"{PatientCardLocators.CD4_MATERIAL_RECEIPT_DATE}.val('{self.today}');")
        # self.browser.execute_script(f"{PatientCardLocators.CD4_SAMPLE_RECEIPT_DATE}.val('{self.today}');")
        # self.browser.execute_script(f"{PatientCardLocators.CD4_REGISTERING_DATE}.val('{self.today}');")
        # self.browser.execute_script(f"{PatientCardLocators.CD4}.val('1');")
        # self.browser.execute_script(f"{PatientCardLocators.CD3}.val('2');")
        # self.browser.execute_script(f"{PatientCardLocators.CD8}.val('2');")
        # self.browser.execute_script(f"{PatientCardLocators.CD4_CD8}.val('2');")
        # self.browser.execute_script(f"{PatientCardLocators.CD4_rate}.val('2');")
        # self.browser.execute_script(f"{PatientCardLocators.CD4_MED_ORG_PROVIDED_ANALYSIS}.dropdown('set selected', '{self.mo_choice1}');")
        # self.browser.execute_script(f"{PatientCardLocators.CD4_REMARK}.val('Положительный');")
        # service_choice = random.choice(['304', '238'])
        # self.browser.execute_script(f"{PatientCardLocators.CD4_SERVICES}.dropdown('set selected', '{service_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.CD4_SAVE}.click();")
        # sleep(2)
        # self.browser.execute_script(f"{PatientCardLocators.VIRAL_LOAD_ADD}.click();")
        # self.browser.execute_script(f"{PatientCardLocators.VL_ANALYSIS_NUM}.val('{self.numbers5}');")
        # self.browser.execute_script(f"{PatientCardLocators.VL_DONOR_MED_ORG}.dropdown('set selected', '{self.mo_choice1}');")
        # self.browser.execute_script(f"{PatientCardLocators.VL_MATERIAL_RECEIPT_DATE}.val('{self.today}');")
        # self.browser.execute_script(f"{PatientCardLocators.VL_MATERIAL_SAMPLING_DATE}.val('{self.today}');")
        # self.browser.execute_script(f"{PatientCardLocators.VL_REGISTERING_DATE}.val('{self.today}');")
        # vl_res_choice = random.choice(['0', '1', '2'])
        # self.browser.execute_script(f"{PatientCardLocators.VL_RESULT}.dropdown('set selected', '{vl_res_choice}');")
        # vl_res_ml_choice = random.randint(150, 500)
        # self.browser.execute_script(f"{PatientCardLocators.VL_RESULT_ML}.val('{vl_res_ml_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.LOG}.val('2');")
        # self.browser.execute_script(f"{PatientCardLocators.VL_MED_ORG_PROVIDED_ANALYSIS}.dropdown('set selected', '{self.mo_choice1}');")
        # remark_choice = random.choice(['Плановое обследование', 'Внелановое обследование'])
        # self.browser.execute_script(f"{PatientCardLocators.VL_REMARK}.dropdown('set selected', '{remark_choice}');")
        # vl_service_choice = random.choice(['242', '263'])
        # self.browser.execute_script(f"{PatientCardLocators.VL_SERVICES}.dropdown('set selected', '{vl_service_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.VL_SAVE}.click();")
        # sleep(1)
        #
        # self.browser.execute_script(f"{PatientCardLocators.VIRAL_HEPATITIS}.click();")
        # sleep(1)
        # self.browser.execute_script(f"{PatientCardLocators.VGV_ADD}.click();")
        # self.browser.execute_script(f"{PatientCardLocators.VGV_REGISTRATION_NUM}.val('{self.numbers5}');")
        # self.browser.execute_script(f"{PatientCardLocators.VGV_MAT_DONOR_MED_ORG}.dropdown('set selected', '{self.mo_choice1}');")
        # self.browser.execute_script(f"{PatientCardLocators.VGV_MATERIAL_RECEIPT_DATE}.val('{self.today}');")
        # self.browser.execute_script(f"{PatientCardLocators.VGV_REGISTERING_DATE}.val('{self.today}');")
        # marker_choice = random.choice(['0', '1', '2', '3', '4', '5', '6', '7', '8'])
        # self.browser.execute_script(f"{PatientCardLocators.MARKER}.dropdown('set selected', '{marker_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.VGV_RESULT}.dropdown('set selected', '1');")
        # self.browser.execute_script(f"{PatientCardLocators.VGV_MED_ORG_PROVIDED_ANALYSIS}.dropdown('set selected', '{self.mo_choice1}');")
        # self.browser.execute_script(f"{PatientCardLocators.VGV_REMARK}.val('Положительный');")
        # self.browser.execute_script(f"{PatientCardLocators.VGV_SAVE}.click();")
        # sleep(2)
        # self.browser.execute_script(f"{PatientCardLocators.VGS_ADD}.click();")
        # self.browser.execute_script(f"{PatientCardLocators.VGS_REGISTRATION_NUM}.val('{self.numbers5}');")
        # self.browser.execute_script(f"{PatientCardLocators.VGS_MAT_DONOR_MED_ORG}.dropdown('set selected', '{self.mo_choice1}');")
        # self.browser.execute_script(f"{PatientCardLocators.VGS_MATERIAL_RECEIPT_DATE}.val('{self.today}');")
        # self.browser.execute_script(f"{PatientCardLocators.VGS_REGISTERING_DATE}.val('{self.today}');")
        # analysis_choice = random.choice([ '1', '2', '3', '4'])
        # self.browser.execute_script(f"{PatientCardLocators.VGS_ANALYSIS_TYPE}.dropdown('set selected', '{analysis_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.VGS_RESULT}.dropdown('set selected', '1');")
        # self.browser.execute_script(f"{PatientCardLocators.VGS_MED_ORG_PROVIDED_ANALYSIS}.dropdown('set selected', '{self.mo_choice1}');")
        # self.browser.execute_script(f"{PatientCardLocators.VGS_REMARK}.val('Положительный');")
        # self.browser.execute_script(f"{PatientCardLocators.VGS_SAVE}.click();")
        # sleep(2)
        # self.browser.execute_script(f"{PatientCardLocators.VGV_VAC_ADD}.click();")
        # vac_multi_choice = random.choice(['0', '1', '2', '3', '4', '5', '6', '7', '8'])
        # self.browser.execute_script(f"{PatientCardLocators.VGV_VAC_MULTIPLICITY}.dropdown('set selected', '{vac_multi_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.IMMUNIZATION_DATE}.calendar('set date', '{self.today}');")
        # dose = random.choice(['5', '10', '15'])
        # self.browser.execute_script(f"{PatientCardLocators.VGV_VAC_DOSE_VOLUME}.val('{dose}');")
        # self.browser.execute_script(f"{PatientCardLocators.VGV_VAC_SERIES}.val('{self.numbers5}');")
        # vac_multi_choice = random.choice(['США', 'Казахстан', 'Россия', 'Китай', 'Южная Корея', 'Индия', 'Япония', 'Германия', 'Турция'])
        # self.browser.execute_script(f"{PatientCardLocators.VGV_VAC_COUNTRY_PRODUCER}.val('{vac_multi_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.MED_ORG_PROVIDED_VACCINATION}.dropdown('set selected', '{self.mo_choice1}');")
        # self.browser.execute_script(f"{PatientCardLocators.VGV_VAC_SAVE}.click();")
        #
        # self.browser.execute_script(f"{PatientCardLocators.TUBERCULOSIS}.click();")
        # self.browser.execute_script(f"{PatientCardLocators.FLUOROSCOPY_ADD}.click();")
        # self.browser.execute_script(f"{PatientCardLocators.FLUOR_REGISTERING_DATE}.calendar('set date', '{self.today}');")
        # fluor_choice = random.choice(['1', '2', '3', '4', '5'])
        # self.browser.execute_script(f"{PatientCardLocators.FLUOR_RESULT}.dropdown('set selected', '{fluor_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.FLUOROSCOPY_SAVE}.click();")
        #
        # self.browser.execute_script(f"{PatientCardLocators.RADIOGRAPHY_ADD}.click();")
        # self.browser.execute_script(f"{PatientCardLocators.RADIO_REGISTERING_DATE}.calendar('set date', '{self.today}');")
        # radio_choice = random.choice(['1', '2', '3', '4', '5'])
        # self.browser.execute_script(f"{PatientCardLocators.RADIO_RESULT}.dropdown('set selected', '{radio_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.RADIOGRAPHY_SAVE}.click();")
        #
        # self.browser.execute_script(f"{PatientCardLocators.SPUTUM_SMEAR_EXAMINATION_ADD}.click();")
        # self.browser.execute_script(f"{PatientCardLocators.SPUTUM_REGISTERING_DATE}.calendar('set date', '{self.today}');")
        # sputum_choice = random.choice(['1', '2', '3', '4', '5'])
        # self.browser.execute_script(f"{PatientCardLocators.SPUTUM_RESULT}.dropdown('set selected', '{sputum_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.SPUTUM_SAVE}.click();")
        #
        # self.browser.execute_script(f"{PatientCardLocators.TB_SYMPHTOMS_ADD}.click();")
        # self.browser.execute_script(f"{PatientCardLocators.TB_SYMPH_REGISTERING_DATE}.calendar('set date', '{self.today}');")
        # tb_symph_choice = random.choice(['1', '2'])
        # self.browser.execute_script(f"{PatientCardLocators.TB_SYMPH_RESULT}.dropdown('set selected', '{tb_symph_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.TB_SYMPH_SAVE}.click();")
        #
        # self.browser.execute_script(f"{PatientCardLocators.XPERT_MTB_ADD}.click();")
        # self.browser.execute_script(f"{PatientCardLocators.XPERT_MTB_REGISTERING_DATE}.calendar('set date', '{self.today}');")
        # xpert_choice = random.choice(['1', '2', '3', '4', '5'])
        # self.browser.execute_script(f"{PatientCardLocators.XPERT_MTB_RESULT}.dropdown('set selected', '{xpert_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.XPERT_MTB_SAVE}.click();")
        #
        # self.browser.execute_script(f"{PatientCardLocators.KT_MRT_ADD}.click();")
        # self.browser.execute_script(f"{PatientCardLocators.KT_MRT_REGISTERING_DATE}.calendar('set date', '{self.today}');")
        # mrt_choice = random.choice(['1', '2', '3', '4', '5'])
        # self.browser.execute_script(f"{PatientCardLocators.KT_MRT_RESULT}.dropdown('set selected', '{mrt_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.KT_MRT_SAVE}.click();")
        #
        # self.browser.execute_script(f"{PatientCardLocators.TB_TREATMENT_ADD}.click();")
        # self.browser.execute_script(f"{PatientCardLocators.LAB_NAME_CONFIRMED_TB}.val('Random lab');")
        # # self.browser.execute_script(f"{PatientCardLocators.TB_DIAG_REGISTERING_DATE}.val('01.01.2021');")
        # case_choice = random.choice(['9', '1', '2', '3', '4', '5', '6', '7', '8'])
        # self.browser.execute_script(f"{PatientCardLocators.SICK_TYPE}.dropdown('set selected', '{case_choice}');")
        # analysis_choice = random.choice(['35', '1', '2', '3', '4', '5', '6', '7', '47'])
        # self.browser.execute_script(f"{PatientCardLocators.TB_DIAG_MKB10}.dropdown('set selected', '{analysis_choice}');")
        # location1_choice = random.choice(['1', '2', '1111', '1112'])
        # self.browser.execute_script(f"{PatientCardLocators.LOCATION}.dropdown('set selected', '{location1_choice}');")
        # # self.browser.execute_script(f"{PatientCardLocators.TREATMENT_START_DATE}.val('{self.today}');")
        # # self.browser.execute_script(f"{PatientCardLocators.TREATMENT_END_DATE}.val('{self.today}');")
        # bac_secr_choice = random.choice(['1', '2'])
        # self.browser.execute_script(f"{PatientCardLocators.BAC_SECRETION}.dropdown('set selected', '{bac_secr_choice}');")
        # outcome_choice = random.choice(['1', '2', '3', '4', '5', '6', '7', '8'])
        # self.browser.execute_script(f"{PatientCardLocators.OUTCOME}.dropdown('set selected', '{outcome_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.TB_TREATMENT_SAVE}.click();")
        # tb_hist_choice = random.choice(['1', '2'])
        # self.browser.execute_script(f"{PatientCardLocators.PRESENCE_TB_IN_HISTORY}.dropdown('set selected', '{tb_hist_choice}');")
        # self.browser.execute_script(f"{PatientCardLocators.D_ACCOUNTED_DATE}.calendar('set date', '{self.today}');")

        self.browser.execute_script(f"{PatientCardLocators.CHILDREN_PREGNANCY}.click();")
        self.browser.execute_script(f"{PatientCardLocators.PREGNANCY_ADD}.click();")
        pregnancy_choice = random.choice(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'])
        self.browser.execute_script(f"{PatientCardLocators.PREGNANCY}.dropdown('set selected', '{pregnancy_choice}');")
        preg_partner_choice = random.choice(['1', '2', '3'])
        self.browser.execute_script(f"{PatientCardLocators.PREG_SEX_PARTNER}.dropdown('set selected', '{preg_partner_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.PREG_PARTNER_HIV_STATUS}.dropdown('set selected', '{self.hiv_status_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.OGC_REGIS_DATE}.val('{self.regis_date}');")
        preg_weeks_choice = random.choice(['1', '12', '2', '3', '4', '5', '6', '7', '8', '9', '10', '31', '42'])
        self.browser.execute_script(f"{PatientCardLocators.OGC_PREGNANCY_WEEKS}.dropdown('set selected', '{preg_weeks_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.ANTENATAL_CLINIC_REGIS_DATE}.val('{self.regis_date}');")
        self.browser.execute_script(f"{PatientCardLocators.AC_PREGNANCY_WEEKS}.dropdown('set selected', '{preg_weeks_choice}');")
        preg_res_choice = random.choice(['1', '12', '2', '3', '4', '5', '6', '7', '8', '9', '11', '13'])
        self.browser.execute_script(f"{PatientCardLocators.PREGNANCY_RESULT}.dropdown('set selected', '{preg_res_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.PREGNANCY_RESULT_DATE}.val('{self.today}');")
        preg_arv_proph_choice = random.choice(['1', '2'])
        self.browser.execute_script(f"{PatientCardLocators.PREG_ARV_PROPHILAXYS}.dropdown('set selected', '{preg_arv_proph_choice}');")
        if preg_arv_proph_choice == 1:
            self.browser.execute_script(f"{PatientCardLocators.PREG_ARV_PROPH_START_DATE}.val('{self.contacting_num}');")
            self.browser.execute_script(f"{PatientCardLocators.PREGNANCY_WEEKS_ARV_START}.dropdown('set selected', '{preg_weeks_choice}');")
            self.browser.execute_script(f"{PatientCardLocators.PREG_ARV_PROPH_END_DATE}.val('{self.today}');")
            self.browser.execute_script(f"{PatientCardLocators.PREGNANCY_WEEKS_ARV_END}.dropdown('set selected', '{preg_weeks_choice}');")
            preg_medic_choice = random.choice(['1', '12', '2', '3', '4', '5', '6', '7', '8', '9', '10', '31', '211'])
            self.browser.execute_script(f"{PatientCardLocators.PREG_ARV_MEDICATIONS}.dropdown('set selected', '{preg_medic_choice}');")
            self.browser.execute_script(f"{PatientCardLocators.PREG_ARV_ISSUANCE}.click();")
            self.browser.execute_script(f"{PatientCardLocators.PREG_ARV_ISSUANCE_ADD}.click();")
            self.browser.execute_script(f"{PatientCardLocators.PREG_ARV_MEDICATION_NAME}.click();")
            self.browser.execute_script(f"{PatientCardLocators.PREG_ARV_MEDICATION_NAME_CHOICE}.click();")
            self.browser.execute_script(f"{PatientCardLocators.PREG_ARV_RECIPE_NUM}.val('{self.numbers4}');")
            self.browser.execute_script(f"{PatientCardLocators.PREG_ARV_MEDICATION_SAVE}.click();")
            self.browser.execute_script(f"{PatientCardLocators.PREG_ARV_ISSUANCE_SAVE}.click();")
            self.browser.execute_script(f"{PatientCardLocators.PREG_ARV_ISSUANCE_CHILD}.click();")
        self.browser.execute_script(f"{PatientCardLocators.CHILD_ARV_ISSUANCE_ADD}.click();")
        self.browser.execute_script(f"{PatientCardLocators.CHILD_ARV_MEDICATION_NAME}.click();")
        self.browser.execute_script(f"{PatientCardLocators.CHILD_ARV_MEDICATION_NAME_CHOICE}.click();")
        self.browser.execute_script(f"{PatientCardLocators.CHILD_ARV_RECIPE_NUM}.val('{self.numbers5}');")
        self.browser.execute_script(f"{PatientCardLocators.CHILD_ARV_MEDICATION_SAVE}.click();")
        self.browser.execute_script(f"{PatientCardLocators.CHILD_ARV_ISSUANCE_SAVE}.click();")
        self.browser.execute_script(f"{PatientCardLocators.INFORMATION_CHILDREN_ADD}.click();")
        child_choice = random.choice(['1', '2'])
        self.browser.execute_script(f"{PatientCardLocators.ALIVE_CHILD}.dropdown('set selected', '{child_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.CHILDS_SURNAME}.val('{self.surname}');")
        self.browser.execute_script(f"{PatientCardLocators.CHILDS_NAME}.val('{self.name}');")
        self.browser.execute_script(f"{PatientCardLocators.CHILDS_MIDNAME}.val('{self.midname}');")
        self.browser.execute_script(f"{PatientCardLocators.CHILDS_BIRTHDAY}.val('{self.birthday}');")
        self.browser.execute_script(f"{PatientCardLocators.CHILDS_GENDER}.dropdown('set selected', '{self.gen_choice1}');")
        pathology_choice = random.choice(['1', '2'])
        self.browser.execute_script(f"{PatientCardLocators.PATHALOGY_AT_BIRTH}.dropdown('set selected', '{pathology_choice}');")
        feeding_choice = random.choice(['1', '2', '3'])
        self.browser.execute_script(f"{PatientCardLocators.FEEDING}.dropdown('set selected', '{feeding_choice}');")
        full_term_choice = random.choice(['1', '2'])
        self.browser.execute_script(f"{PatientCardLocators.FULL_TERM_CHILD}.dropdown('set selected', '{full_term_choice}');")
        self.browser.excute_script(f"{PatientCardLocators.CHILDS_DEATH_DATE}.val('{self.deregis_date}');")
        self.browser.execute_script(f"{PatientCardLocators.INFORMATION_CHILDREN_SAVE}.click();")
        self.browser.execute_script(f"{PatientCardLocators.PREGNANCY_SAVE}.click();")

        self.browser.execute_script(f"{PatientCardLocators.THERAPHY}.click();")
        sleep(1)
        self.browser.execute_script(f"{PatientCardLocators.PREVENTIVE_THERAPHY_ADD}.click();")
        prev_med_choice = random.choice(['1', '2'])
        self.browser.execute_script(f"{PatientCardLocators.PREV_THER_MEDICATION}.dropdown('set selected', '{prev_med_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.REASONS_SET_DATE}.val('{self.today}');")
        self.browser.execute_script(f"{PatientCardLocators.PREV_THER_START_DATE}.val('{self.today}');")
        self.browser.execute_script(f"{PatientCardLocators.PREV_THER_END_DATE}.val('{self.today}');")
        self.browser.execute_script(f"{PatientCardLocators.PREV_THER_SAVE}.click();")
        sleep(2)
        self.browser.execute_script(f"{PatientCardLocators.OPIOID_SUBSTITUTION_THERAPHY_ADD}.click();")
        self.browser.execute_script(f"{PatientCardLocators.OST_START_DATE}.val('{self.today}');")
        self.browser.execute_script(f"{PatientCardLocators.OST_END_DATE}.val('{self.today}');")
        ost_med_choice = random.choice(['1', '2'])
        self.browser.execute_script(f"{PatientCardLocators.OST_MEDICATION_TYPE}.dropdown('set selected', '{ost_med_choice}');")
        # reas_fin_choice = random.choice(['1', '2'])
        # self.browser.execute_script(f"{PatientCardLocators.REASONS_OF_FINISHING}.dropdown('set selected', '{reas_fin_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.OST_SAVE}.click();")
        sleep(2)
        self.browser.execute_script(f"{PatientCardLocators.VGS_TREATMENT_ADD}.click();")
        self.browser.execute_script(f"{PatientCardLocators.VGS_TREAT_START_DATE}.val('{self.today}');")
        sleep(1)
        self.browser.execute_script(f"{PatientCardLocators.VGS_TREAT_END_DATE}.val('{self.today}');")
        treat_res_choice = random.choice(['1', '2', '3', '4', '5', '6', '7'])
        self.browser.execute_script(f"{PatientCardLocators.VGS_TREAT_RESULT}.dropdown('set selected', '{treat_res_choice}');")
        self.browser.execute_script(f"{PatientCardLocators.VGS_TREAT_SAVE}.click();")
        sleep(1)

        self.browser.execute_script(f"{PatientCardLocators.D_EXAM_HOSPITALIZATION}.click();")
        # self.browser.execute_script(f"{PatientCardLocators.D_EXAM_ADD}.click();")
        ATTENDANCE_DATE = "$('#visit_table_date_visit')"
        D_EXAM_HELD = "$('div[data-field=visit_table_who_conducted] .ui.dropdown')"
        D_SERVICES = "$('div[data-field=visit_table_which_services] .ui.dropdown')"
        D_EXAM_PLACE = "$('div[data-field=visit_table_place_of_inspection] .ui.dropdown')"
        ATTENDANCE_TYPE = "$('div[data-field=visit_table_visit_type] .ui.dropdown')"
        TEMPERATURE = "$('#row_for_total_info_table div[data-field=ljv_card_table_temp]')"
        WEIGHT = "$('#row_for_total_info_table div[data-field=ljv_card_table_weight]')"
        HEIGHT = "$('#row_for_total_info_table div[data-field=ljv_card_table_growth]')"
        COMPLAINTS = "$('#complaints')"
        HISTORY_INFORMATION = "$('#anamnez_data')"
        LAST_MENSIS = "$('input[name=last_mensis]')"
        self.browser.execute_script(f"{PatientCardLocators.CONTRACEPTION}.click();")
        self.browser.execute_script(f"{PatientCardLocators.D_EXAM_SEX_PARTNER}.click();")
        self.browser.execute_script(f"{PatientCardLocators.ART_RECEIPT}.click();")
        self.browser.execute_script(f"{PatientCardLocators.PLANNED_PREGNANCY_YES}.click();")
        self.browser.execute_script(f"{PatientCardLocators.PLANNED_PREGNANCY_NO}.click();")
        self.browser.execute_script(f"{PatientCardLocators.D_EXAM_ALCOHOL}.click();")
        self.browser.execute_script(f"{PatientCardLocators.D_EXAM_DRUGS}.click();")
        D_EXAM_INJ_DRUG_LAST_HALF_YEAR = "$('div[data-field=inek_nark_six_month] .ui.dropdown')"
        D_EXAM_COM_SEX_LAST_HALF_YEAR = "$('div[data-field=komerc_sex_six_month] .ui.dropdown')"
        D_EXAM_HOMO_SEX_LAST_HALF_YEAR = "$('div[data-field=gomo_sex_six_month] .ui.dropdown')"
        STATE = "$('div[data-field=sostoyanie] .ui.dropdown')"
        CONSCIOUSNESS = "$('div[data-field=soznanie] .ui.dropdown')"
        POSITION = "$('div[data-field=polojenie] .ui.dropdown')"
        BODY_TYPE = "$('div[data-field=teloslojenie] .ui.dropdown')"
        FEEDING = "$('div[data-field=pitanie] .ui.dropdown')"
        LIPODYSTROPHY = "$('div[data-field=lipodistrofiya] .ui.dropdown')"
        SKIN_MUCOSA = "$('div[data-field=kojnie_pokrovy_slizistaya] .ui.dropdown')"
        NAILS = "$('div[data-field=nails] .ui.dropdown')"
        RASH = "$('div[data-field=rash] .ui.dropdown')"
        PERIFEPHERAL_LYMPH_NODES = "$('div[data-field=peripheral_lymphnodes] .ui.dropdown')"
        OSTEO_ARTICULAR_SYSTEM = "$('div[data-field=osteo_articular_system] .ui.dropdown')"
        BREATH_SOUNDS = "$('div[data-field=breath] .ui.dropdown')"
        self.browser.execute_script(f"{PatientCardLocators.WHEEZING_YES}.click();")
        self.browser.execute_script(f"{PatientCardLocators.WHEEZING_NO}.click();")
        WHEEZING_TYPE = "$('div[data-field=which_wheezing] .ui.dropdown')"
        RESPIRATORY_RATE = "$('#chdd_min_input')"
        HEART_SOUNDS = "$('div[data-field=heart_sounds] .ui.dropdown')"
        HEART_RATE = "$('#chss_min_input')"
        BLOOD_PREASURE = "$('#davlenie')"
        NOISE = "$('div[data-field=noise] .ui.dropdown')"
        TONGUE = "$('div[data-field=tongue] .ui.dropdown')"
        ORAL_MUCOSA = "$('#oral_mucosa')"
        STOMACH = "$('div[data-field=stomach] .ui.dropdown')"
        LIVER = "$('div[data-field=liver] .ui.dropdown')"
        SPLEEN = "$('div[data-field=spleen] .ui.dropdown')"
        SYMPTOMS_OF_BANGING = "$('div[data-field=symptom_tapping] .ui.dropdown')"
        STOOL = "$('div[data-field=stool] .ui.dropdown')"
        STOOL_MULTIPLICITY = "$('#count_stool')"
        self.browser.execute_script(f"{PatientCardLocators.URINATION_FREE}.click();")
        self.browser.execute_script(f"{PatientCardLocators.URINATION_PAINLESS}.click();")
        self.browser.execute_script(f"{PatientCardLocators.URINATION_PAINFUL}.click();")
        self.browser.execute_script(f"{PatientCardLocators.DIURESIS_FREQUENT}.click();")
        self.browser.execute_script(f"{PatientCardLocators.DIURESIS_BREACHED}.click();")
        self.browser.execute_script(f"{PatientCardLocators.DIURESIS_NORM}.click();")
        SWELLING = "$('#edemas')"
        D_EXAM_DIAGNOSIS = "$('#diagnozis')"
        D_EXAM_NOTES = "$('#description')"
        PLANNED_D_EXAM = "$('input[value name=date_plan_d_osmotr]')"
        self.browser.execute_script(f"{PatientCardLocators.D_EXAM_SAVE}.click();")

    #

    #     self.browser.find_element(*PatientCardLocators.OPEN_PATIENT_CARD).click()
    #     self.browser.find_element(*PatientCardLocators.TARIFIKATOR).click()
    #     self.browser.find_element(*PatientCardLocators.OPEN_PATIENT_CARD).click()
    #     self.browser.find_element(*PatientCardLocators.PRINT).click()
    #     self.browser.find_element(*PatientCardLocators.OPEN_PATIENT_CARD).click()
    #     self.browser.find_element(*PatientCardLocators.SMS_EMAIL).click()
    #     self.browser.find_element(*PatientCardLocators.PHONE_NUMBER).send_keys("87001592322")
    #     self.browser.find_element(*PatientCardLocators.EMAIL).send_keys("ivanov@mail.ru")
    #     self.browser.find_element(*PatientCardLocators.SMS_D_SEARCH).click()
    #     self.browser.find_element(*PatientCardLocators.EMAIL_D_SEARCH).click()
    #     self.browser.find_element(*PatientCardLocators.SMS_ART).click()
    #     self.browser.find_element(*PatientCardLocators.EMAIL_ART).click()
    #     self.browser.find_element(*PatientCardLocators.SMS_FLG).click()
    #     self.browser.find_element(*PatientCardLocators.EMAIL_FLG).click()
    #     self.browser.find_element(*PatientCardLocators.SMS_CD4).click()
    #     self.browser.find_element(*PatientCardLocators.EMAIL_CD4).click()
    #     self.browser.find_element(*PatientCardLocators.SMS_VN).click()
    #     self.browser.find_element(*PatientCardLocators.EMAIL_VN).click()
    #     self.browser.find_element(*PatientCardLocators.SMS_EMAIL_SAVE).click()
    #
    #
    #
    #
    # def register_new_bomj_and_edit_card(self):
    #     # автозаполнение формы регистрации для бомжа
    #     res_code_choice = random.choice(['3', '4', '16'])
    #     self.browser.execute_script(
    #         f"{RegisterPageLocators.RESEARCH_CODE}.dropdown('set selected', '{res_code_choice}');")
    #     d1 = datetime.strptime('01.01.1970', '%d.%m.%Y')
    #     d2 = datetime.strptime('01.12.2000', '%d.%m.%Y')
    #     delta = d2 - d1
    #     int_delta = delta.days
    #     random_date = d1 + timedelta(randrange(int_delta))
    #     first_numbers = random_date.strftime('%y%m%d')
    #     birthday = random_date.strftime('%d.%m.%Y')
    #     others = random.randrange(100000, 999999)
    #     iin = f'{first_numbers}{others}'
    #     self.browser.find_element(*RegisterPageLocators.PATIENT_IIN).send_keys(iin)
    #     self.browser.find_element(*RegisterPageLocators.ANONIMOUS).click()
    #     surname = ''.join(random.choices(string.ascii_uppercase, k=10))
    #     self.browser.find_element(*RegisterPageLocators.PATIENT_SURNAME).send_keys(surname)
    #     name = ''.join(random.choices(string.ascii_uppercase, k=5))
    #     self.browser.find_element(*RegisterPageLocators.PATIENT_NAME).send_keys(name)
    #     midname = ''.join(random.choices(string.ascii_uppercase, k=10))
    #     self.browser.find_element(*RegisterPageLocators.PATIENT_MIDNAME).send_keys(midname)
    #     # self.browser.execute_script(f"$('{RegisterPageLocators.BIRTH_DATE}').val('{birthday}')")
    #     self.browser.execute_script(f"$('#general_data_birth').val('{birthday}')")
    #     gen_choice = random.choice(['female', 'male'])
    #     self.browser.execute_script(f"{RegisterPageLocators.PATIENT_GENDER}.dropdown('set selected', '{gen_choice}');")
    #
    #     self.browser.execute_script(f"{RegisterPageLocators.EMERGENCE_AREA}.dropdown('set selected', '3');")
    #     # self.browser.execute_script(f"{RegisterPageLocators.EMERGENCE_UNIT_AREA}.dropdown('show');")
    #     self.browser.find_element(f"{RegisterPageLocators.EMERGENCE_UNIT_AREA}.dropdown();").click()
    #     self.browser.execute_script(f"{RegisterPageLocators.EMERGENCE_UNIT_AREA}.dropdown('set value', '33');")
    #     self.browser.execute_script(
    #         f"{RegisterPageLocators.PATIENT_CITIZENSHIP}.dropdown('set selected', 'without-citizenship');")
    #     soc_status_choice = random.choice(['4', '8'])
    #     self.browser.execute_script(
    #         f"{RegisterPageLocators.SOCIAL_STATUS}.dropdown('set selected', '{soc_status_choice}');")
    #     self.browser.execute_script(f"{RegisterPageLocators.BOMJ_CHECKBOX}.checkbox('set checked');")
    #     med_org_choice = random.choice(['170000000003', '170000000105', '170000000004', '170000000008', '170000000009'])
    #     self.browser.execute_script(f"{RegisterPageLocators.MED_ORG}.dropdown('set selected', '{med_org_choice}');")
    #     self.browser.find_element(*RegisterPageLocators.REGISTER_SAVE_BTN).click()


    def register_new_citizen_and_edit_card(self):
        # автозаполнение формы регистрации для взрослого казахстанца
        res_code_choice = random.choice(['47', '48', '11', '22'])
        self.browser.execute_script(
            f"{RegisterPageLocators.RESEARCH_CODE}.dropdown('set selected', '{res_code_choice}');")
        d1 = datetime.strptime('01.01.1970', '%d.%m.%Y')
        d2 = datetime.strptime('01.12.2003', '%d.%m.%Y')
        delta = d2 - d1
        int_delta = delta.days
        random_date = d1 + timedelta(randrange(int_delta))
        first_numbers = random_date.strftime('%y%m%d')
        birthday = random_date.strftime('%d.%m.%Y')
        others = random.randrange(100000, 999999)
        iin = f'{first_numbers}{others}'
        self.browser.find_element(*RegisterPageLocators.PATIENT_IIN).send_keys(iin)
        trans_choice = random.choice(['1', '2'])
        self.browser.execute_script(f"{RegisterPageLocators.TRANSGENDER}.dropdown('set selected', '{trans_choice}');")
        self.browser.find_element(*RegisterPageLocators.ANONIMOUS).click()
        surname = ''.join(random.choices(string.ascii_uppercase, k=10))
        self.browser.find_element(*RegisterPageLocators.PATIENT_SURNAME).send_keys(surname)
        name = ''.join(random.choices(string.ascii_uppercase, k=5))
        self.browser.find_element(*RegisterPageLocators.PATIENT_NAME).send_keys(name)
        midname = ''.join(random.choices(string.ascii_uppercase, k=10))
        self.browser.find_element(*RegisterPageLocators.PATIENT_MIDNAME).send_keys(midname)
        # self.browser.execute_script(f"$('{RegisterPageLocators.BIRTH_DATE}').val('{birthday}')")
        self.browser.execute_script(f"$('#general_data_birth').val('{birthday}')")
        gen_choice = random.choice(['female', 'male'])
        self.browser.execute_script(f"{RegisterPageLocators.PATIENT_GENDER}.dropdown('set selected', '{gen_choice}');")
        self.browser.execute_script(f"{RegisterPageLocators.EMERGENCE_AREA}.dropdown('set selected', '3');")
        self.browser.execute_script(f"{RegisterPageLocators.EMERGENCE_UNIT_AREA}.dropdown('set selected', '33');")
        self.browser.execute_script(
            f"{RegisterPageLocators.PATIENT_CITIZENSHIP}.dropdown('set selected', 'rk-citizen');")
        soc_status_choice = random.choice(['2', '5', '6', '1', '7', '8', '9', '10', '11'])
        self.browser.execute_script(
            f"{RegisterPageLocators.SOCIAL_STATUS}.dropdown('set selected', '{soc_status_choice}');")
        med_org_choice = random.choice(['170000000003', '170000000105', '170000000004', '170000000008', '170000000009'])
        self.browser.execute_script(f"{RegisterPageLocators.MED_ORG}.dropdown('set selected', '{med_org_choice}');")
        self.browser.execute_script(f"{RegisterPageLocators.REGIS_AREA}.dropdown('set selected', '5');")
        self.browser.execute_script(f"{RegisterPageLocators.REGIS_UNIT_AREA}.dropdown('set selected', '191');")
        locality_choice = random.choice(
            ['170000000020', '170000000008', '170000000032', '170000000085', '170000000242', '170000000253'])
        self.browser.execute_script(f"{RegisterPageLocators.REGIS_LOCALITY}.dropdown('set selected', '177');")
        self.browser.execute_script(f"{RegisterPageLocators.REGIS_PLACE}.dropdown('set selected', '2');")
        street_choice = random.choice(['Назарбаев', 'Абай', 'Конаев', 'Кабанбай батыр'])
        self.browser.find_element(*RegisterPageLocators.REGIS_STREET).send_keys(street_choice)
        self.browser.find_element(*RegisterPageLocators.REGIS_HOUSE).send_keys(55)
        self.browser.find_element(*RegisterPageLocators.REGIS_APT).send_keys(44)
        self.browser.find_element(*RegisterPageLocators.REGIS_PHONE_NO).send_keys(87273456987)
        self.browser.execute_script(f"{RegisterPageLocators.RESID_AREA}.dropdown('set selected', '3');")
        self.browser.execute_script(f"{RegisterPageLocators.RESID_UNIT_AREA}.dropdown('set selected', '33');")
        self.browser.execute_script(
            f"{RegisterPageLocators.RESID_LOCALITY}.dropdown('set selected', '{locality_choice}');")
        self.browser.execute_script(f"{RegisterPageLocators.RESID_PLACE}.dropdown('set selected', '2');")
        self.browser.find_element(*RegisterPageLocators.RESID_STREET).send_keys(street_choice)
        self.browser.find_element(*RegisterPageLocators.RESID_HOUSE).send_keys(25)
        self.browser.find_element(*RegisterPageLocators.RESID_APT).send_keys(45)
        self.browser.find_element(*RegisterPageLocators.RESID_PHONE_NO).send_keys(87273456789)
        self.browser.execute_script(f"{RegisterPageLocators.RESID_MED_ORG}.dropdown('set selected', '170000000558');")
        self.browser.find_element(*RegisterPageLocators.REGISTER_SAVE_BTN).click()

    def register_new_foreigner_and_edit_card(self):
        # Регистрация иностранного гражданина
        foreigner_ib_no = ''.join(random.choices(string.digits, k=5))
        self.browser.find_element(*RegisterPageLocators.FOREIGNER_IB_NO).send_keys(foreigner_ib_no)
        date1 = datetime.strptime('01.01.2007', '%d.%m.%Y')
        date2 = datetime.strptime('01.12.2021', '%d.%m.%Y')
        delta = date2 - date1
        int_delta2 = delta.days
        random_date1 = date1 + timedelta(randrange(int_delta2))
        foreigner_ib_no_date = random_date1.strftime('%d.%m.%Y')
        self.browser.find_element(*RegisterPageLocators.FOREIGNER_IB_NO_DATE).send_keys(foreigner_ib_no_date)
        res_code_choice = random.choice(['3', '50', '7', '8', '36', '71', '37', '88', '51'])
        self.browser.execute_script(
            f"{RegisterPageLocators.RESEARCH_CODE}.dropdown('set selected', '{res_code_choice}');")
        d1 = datetime.strptime('01.01.2005', '%d.%m.%Y')
        d2 = datetime.strptime('01.12.2005', '%d.%m.%Y')
        delta = d2 - d1
        int_delta = delta.days
        random_date = d1 + timedelta(randrange(int_delta))
        first_numbers = random_date.strftime('%y%m%d')
        birthday = random_date.strftime('%d.%m.%Y')
        others = random.randrange(100000, 999999)
        iin = f'{first_numbers}{others}'
        self.browser.find_element(*RegisterPageLocators.PATIENT_IIN).send_keys(iin)
        trans_choice = random.choice(['1', '2'])
        self.browser.execute_script(f"{RegisterPageLocators.TRANSGENDER}.dropdown('set selected', '{trans_choice}');")
        self.browser.find_element(*RegisterPageLocators.ANONIMOUS).click()
        surname = ''.join(random.choices(string.ascii_uppercase, k=10))
        self.browser.find_element(*RegisterPageLocators.PATIENT_SURNAME).send_keys(surname)
        name = ''.join(random.choices(string.ascii_uppercase, k=5))
        self.browser.find_element(*RegisterPageLocators.PATIENT_NAME).send_keys(name)
        midname = ''.join(random.choices(string.ascii_uppercase, k=10))
        self.browser.find_element(*RegisterPageLocators.PATIENT_MIDNAME).send_keys(midname)
        # self.browser.execute_script(f"$('{RegisterPageLocators.BIRTH_DATE}').val('{birthday}')")
        self.browser.execute_script(f"$('#general_data_birth').val('{birthday}')")
        gen_choice = random.choice(['female', 'male'])
        self.browser.execute_script(f"{RegisterPageLocators.PATIENT_GENDER}.dropdown('set selected', '{gen_choice}');")
        self.browser.execute_script(f"{RegisterPageLocators.EMERGENCE_AREA}.dropdown('set selected', '3');")
        self.browser.execute_script(f"{RegisterPageLocators.EMERGENCE_UNIT_AREA}.dropdown('set selected', '33');")
        self.browser.execute_script(
            f"{RegisterPageLocators.PATIENT_CITIZENSHIP}.dropdown('set selected', 'foreign-citizen');")
        date1 = datetime.strptime('01.01.2007', '%d.%m.%Y')
        date2 = datetime.strptime('01.12.2021', '%d.%m.%Y')
        delta = date2 - date1
        int_delta1 = delta.days
        random_date1 = date1 + timedelta(randrange(int_delta1))
        arrival_date = random_date1.strftime('%d.%m.%Y')
        self.browser.find_element(*RegisterPageLocators.ARRIVAL_DATE).send_keys(arrival_date)
        country_choice = random.choice(['КИТАЙ', 'ТАДЖИКИСТАН', 'АРМЕНИЯ', 'ДАЛЬНЕЕ ЗАРУБЕЖЬЕ', 'МОЛДОВА', 'ДРУГОЕ'])
        self.browser.execute_script(f"{RegisterPageLocators.COUNTRY_FROM_WHICH_CAME}.dropdown('set selected', '{country_choice}');")
        purpose_choice = random.choice(['1', '2', '3', '4', '5', '6'])
        self.browser.execute_script(f"{RegisterPageLocators.ARRIVAL_PURPOSE}.dropdown('set selected', '{purpose_choice}');")
        soc_status_choice = random.choice(['1', '4'])
        self.browser.execute_script(
            f"{RegisterPageLocators.SOCIAL_STATUS}.dropdown('set selected', '{soc_status_choice}');")
        med_org_choice = random.choice(['170000000003', '170000000105', '170000000004', '170000000008', '170000000009'])
        self.browser.execute_script(f"{RegisterPageLocators.MED_ORG}.dropdown('set selected', '{med_org_choice}');")
        self.browser.execute_script(f"{RegisterPageLocators.REGIS_AREA}.dropdown('set selected', '5');")
        self.browser.execute_script(f"{RegisterPageLocators.REGIS_UNIT_AREA}.dropdown('set selected', '191');")
        locality_choice = random.choice(
            ['170000000020', '170000000008', '170000000032', '170000000085', '170000000242', '170000000253'])
        self.browser.execute_script(f"{RegisterPageLocators.REGIS_LOCALITY}.dropdown('set selected', '177');")
        self.browser.execute_script(f"{RegisterPageLocators.REGIS_PLACE}.dropdown('set selected', '2');")
        street_choice = random.choice(['Назарбаев', 'Абай', 'Конаев', 'Кабанбай батыр'])
        self.browser.find_element(*RegisterPageLocators.REGIS_STREET).send_keys(street_choice)
        self.browser.find_element(*RegisterPageLocators.REGIS_HOUSE).send_keys(55)
        self.browser.find_element(*RegisterPageLocators.REGIS_APT).send_keys(44)
        self.browser.find_element(*RegisterPageLocators.REGIS_PHONE_NO).send_keys(87273456987)
        self.browser.execute_script(f"{RegisterPageLocators.RESID_AREA}.dropdown('set selected', '3');")
        self.browser.execute_script(f"{RegisterPageLocators.RESID_UNIT_AREA}.dropdown('set selected', '33');")
        self.browser.execute_script(f"{RegisterPageLocators.RESID_LOCALITY}.dropdown('set selected', '{self.locality_choice}');")
        self.browser.execute_script(f"{RegisterPageLocators.RESID_PLACE}.dropdown('set selected', '2');")
        self.browser.find_element(*RegisterPageLocators.RESID_STREET).send_keys(street_choice)
        self.browser.find_element(*RegisterPageLocators.RESID_HOUSE).send_keys(25)
        self.browser.find_element(*RegisterPageLocators.RESID_APT).send_keys(45)
        self.browser.find_element(*RegisterPageLocators.RESID_PHONE_NO).send_keys(87273456789)
        self.browser.execute_script(f"{RegisterPageLocators.RESID_MED_ORG}.dropdown('set selected', '170000000558');")
        self.browser.find_element(*RegisterPageLocators.REGISTER_SAVE_BTN).click()

# soc_status_choice = random.choice(['3', '4'])
#         soc_status = f"{RegisterPageLocators.REASON_NOT_COND_EPID_INVTG}.dropdown('set selected', '{soc_status_choice}');"
#         self.browser.execute_script(soc_status)
#         rsn_not_disp_choice = random.choice(['3', '4'])
#         rsn_not_disp = f"{RegisterPageLocators.REASON_NOT_DISP_REG}.dropdown('set selected', '{rsn_not_disp_choice}');"
#         self.browser.execute_script(rsn_not_disp)